Draft: Abstract GasTree algorithm
gear-tech/gear pull request #1101
Opened 2022-06-22 06:25 UTC by gshep

Resolves #1072 

-
-
-

@reviewer-or-team

2022-06-27 20:36 UTC, breathx requested changes
Resolve given comments and provide docs for pallet:
be like this
https://github.com/gear-tech/gear/blob/96089c24a6180021dbdd1f4badb2efae8bd21d55/pallets/gear-messenger/src/lib.rs#L19
and this
https://github.com/gear-tech/gear/blob/96089c24a6180021dbdd1f4badb2efae8bd21d55/pallets/gear-messenger/src/lib.rs#L335

and so on

Great job at all! 👍 🚀

2022-06-27 20:36 UTC, breathx commented on pallets/usage/src/tests.rs
> +            GasHandlerOf::<Test>::create(user_id.into_origin(), msg_id.into_origin(), gas_limit);
for whole `GasTree` api

2022-06-27 20:36 UTC, breathx commented on common/src/gas_provider/error.rs
> +    /// Procedure can't be called on consumed node
```suggestion
    /// Procedure can't be called on consumed node.
```

Dots at the end of each doc comment.

2022-06-27 20:36 UTC, breathx commented on common/src/gas_provider/mod.rs
> +}
This stuff already exists in storage primitives: check `complicated::Limiter`

2022-06-27 20:36 UTC, breathx commented on common/src/gas_provider/node.rs
> +// This file is part of Gear.
please, rename existing structures to `GasNode` and `GasNodeType`

2022-06-27 20:36 UTC, breathx commented on pallets/gas/src/lib.rs
> +        name: ValueTreeNodesWrap,
`GasNodes`
`GasNodesWrap`

2022-06-27 20:36 UTC, breathx commented on pallets/gas/src/lib.rs
> +    pub type ExternalOrigin = H256;
```suggestion
    pub type Key = MessageId;
    pub type ExternalOrigin = Config::AccountId;
```

2022-06-28 07:18 UTC, gshep commented on common/src/gas_provider/negative_imbalance.rs
> +    #[allow(clippy::comparison_chain)]
Good remark, thanks! I just didn't dive too deep into the code when moving it around. Edited

2022-06-29 15:38 UTC, breathx approved these changes
Delicious ❤️

2022-06-30 14:16 UTC, ekovalev approved these changes

2022-06-30 14:22 UTC, merged