Update send_message and send_reply weights
gear-tech/gear pull request #1305
Opened 2022-08-10 12:17 UTC by ukint-vs

Resolves #1203  .

- payload size has almost no effect on execution time
- value can be zero or above minimal balance
- destination can be a program or regular account

@gear-tech/dev

2022-08-15 11:59 UTC, grishasobol approved these changes

2022-08-17 13:53 UTC, breathx requested changes
I don't really like this style of managing weights:
If I were you, I would probably separate weight function on each case we were discussing (here are 3 params: destination, gas limit, value - all of their combinations), and provide some soft function to be used in pallet inside weight macro (that will query data and choose the correct benchmark function).

2022-08-17 13:53 UTC, breathx commented on pallets/gear/src/benchmarking/mod.rs
>          let caller = benchmarking::account("caller", 0, 0);
If we add here following line: `log::debug!("v: {v} p: {p}");`
then following commands
```shell
$ cargo build -p gear-node --release --features runtime-benchmarks
$ RUST_LOG=pallet_gear=debug ./target/debug/gear-node benchmark pallet --chain=dev \
--steps=1 --repeat=1 --pallet=pallet_gear --extrinsic="send_message" --execution=wasm \
--wasm-execution=compiled --heap-pages=4096
```
show that there is no case when v = 0 p = 0

2022-08-26 12:58 UTC, NikVolf commented on pallets/gear/src/lib.rs
> +            if GearProgramPallet::<T>::program_exists(*destination) {
weight calculation formula should not include database reads imho

2022-09-05 12:51 UTC, breathx commented
Temporary closing as stale one

2022-09-05 12:51 UTC, closed without merging