Add interaction with meta data
gear-tech/gear pull request #147
Opened 2021-08-20 11:12 UTC by breathx

2021-08-20 17:13 UTC, NikVolf requested changes
Other than moving it all to separate crate lgtm

2021-08-20 17:13 UTC, NikVolf commented on gstd/Cargo.toml
> +scale-info = { version = "0.10.0", default-features = false, features = ["derive", "serde"] }
Nothing of this should be a dependency of gstd 

this should go to gstd-meta or similar

2021-08-23 11:18 UTC, NikVolf commented on gstd-meta/codegen/src/lib.rs
> +    let derive_string = String::from("#[derive(Debug, Decode, Encode, TypeInfo)]");
this is not needed (the whole `#[gear_data]` thing)

user is quite capable of putting `#[derive(Debug, Decode, Encode, TypeInfo)]` on his own

2021-08-23 11:19 UTC, NikVolf commented
The js-test with meta should be extended to test dynamically generated type info-s

2021-08-28 15:44 UTC, closed without merging

2021-08-28 15:45 UTC, breathx commented
Moved to separate PR's with fixes