feat(gprogram): export rpc calls from Api
gear-tech/gear pull request #1798
Opened 2022-11-08 16:29 UTC by clearloop

Resolves #1780 

- move rpc module from signer to api
-

@gear-tehc/dev

2022-11-09 20:13 UTC, SabaunT commented
Can we see a couple of tests in 'gclient' of rpc calls?

2022-11-10 13:27 UTC, breathx requested changes
Agree with @SabaunT, some tests are required just for demonstration
Otherwise lgtm!

2022-11-10 13:27 UTC, breathx commented on program/src/api/rpc.rs
> +                    H256(Default::default()),
why source removed?

2022-11-10 13:27 UTC, breathx commented on program/src/api/rpc.rs
> +                    H256(Default::default()),
this thing may affect calculate gas logic

2022-11-10 13:27 UTC, breathx commented on gclient/src/api/mod.rs
> +impl Deref for GearApi {
Do we really need all methods of Signer available for GearApi?

2022-11-12 01:21 UTC, breathx approved these changes
I'd make source argument optional and paste self id in case of none

2022-11-12 01:21 UTC, breathx commented on program/src/api/rpc.rs
> +                    u64::try_from(value).unwrap_or(u64::MAX),
do we really can't throw here u128? use [u8; 16] instead for rpc calls also

2022-11-12 01:22 UTC, breathx commented
Add and similar bindings for `gclient`, please!

2022-11-13 23:44 UTC, breathx commented on program/src/api/rpc.rs
> +                    u64::try_from(value).unwrap_or(u64::MAX),
we never used u64 for value
If I'm not mistaken, rpc params macro wasn't able to use it for some reason

2022-11-14 13:19 UTC, merged