Charge for reservation holding
gear-tech/gear pull request #1854
Opened 2022-11-16 22:34 UTC by ark0f

Resolves #1830

2022-11-23 09:47 UTC, breathx requested changes

2022-11-23 09:47 UTC, breathx commented on core-processor/src/ext.rs
> +        // TODO: amount != 0
resolve your own todos

2022-11-23 09:47 UTC, breathx commented on core-processor/src/ext.rs
> +            return self.return_and_store_err(Err(ExecutionError::InsufficientGasForReservation));
why not add them up to reduce once?

2022-11-23 09:47 UTC, breathx commented on core/src/message/context.rs
> +    // TODO: introduce reservation fee
todo

2022-11-23 09:47 UTC, breathx commented on core/src/reservation.rs
> +    pub fn into_map<F>(self, start: u32, duration_into_expiration: F) -> GasReservationMap
I'd rename to not mess up with start from existing reservation state

2022-11-23 09:47 UTC, breathx commented on pallets/gear/src/manager/journal.rs
>              unreachable!("Threshold for reservation invalidated")
without validation on zero duration you can run into this unreachable - need test also

2022-11-23 09:47 UTC, breathx commented on pallets/gear/src/manager/mod.rs
>  pub use journal::*;
https://github.com/gear-tech/gear/blob/23aa9ef2c84062056589d0b54250dce92b6cef1b/pallets/gear/src/manager/task.rs#L145-L147
This seems tricky for me, I'd go with renaming into `remove_gas_reservation_impl` for manager's not-trait fn cause it's not intuitive atm and MAY depend on compiler (which fn to call, probability of inf recursion)

2022-11-23 09:47 UTC, breathx commented on pallets/gear/src/tests.rs
> +
assert balances here?

2022-11-23 09:47 UTC, breathx commented on pallets/gear/src/tests.rs
> +
of accounts I mean, not reservations

2022-11-23 09:47 UTC, breathx commented on pallets/gear/src/tests.rs
> +
and for other blocks if needed also

2022-11-23 09:47 UTC, breathx commented on pallets/gear/src/tests.rs
> +        assert_eq!(map.len(), 1);
balances

2022-11-23 09:47 UTC, breathx commented on pallets/gear/src/tests.rs
> +        // `gr_exit` occurs
just for confidence, do we have test for wait+wake in init and further termination for common reservations and system one?

2022-11-23 09:47 UTC, breathx commented on pallets/gear/src/tests.rs
> +        // `gr_exit` occurs
and gr_exit test for system reservation with a)wait+wake and b)during the single execution

2022-11-23 09:47 UTC, breathx commented on runtime/gear/src/lib.rs
> +    spec_version: 240,
spec_version: 100

2022-11-30 17:00 UTC, breathx requested changes

2022-11-30 20:25 UTC, ark0f commented on pallets/gear/src/manager/journal.rs
>              common::set_program(pid, prog);
And we don't do this

2022-12-06 01:39 UTC, breathx approved these changes

2022-12-06 01:42 UTC, ark0f commented on examples/binaries/signal-entry/src/lib.rs
> +                exec::system_reserve_gas(900).unwrap();
#1951

2022-12-06 18:03 UTC, merged