[don't merge] Vara: Rolling changes
gear-tech/gear pull request #1878
Opened 2022-11-21 18:19 UTC by NikVolf

This is to keep CI running on vara branch

2022-11-21 18:31 UTC, breathx requested changes
This files are also deprecated: 
- pallets/gear-program/weights/pallet_gear_program.rs
- program/api/generated/metadata.rs

2022-11-21 18:31 UTC, breathx commented on scripts/gear.sh
> +      uploads)
Dead test

2022-11-21 18:31 UTC, breathx commented on scripts/test-utils/harmlessUploadDemos.js
> +const { ApiPromise, WsProvider, Keyring } = require('@polkadot/api');
Dead test

2022-11-21 18:31 UTC, breathx commented on scripts/test-utils/infiniteLoop.js
> +const { randomAsHex } = require('@polkadot/util-crypto');
Dead test

2022-11-21 18:31 UTC, breathx commented on runtime/gear/src/lib.rs
> +    spec_version: 130,
I'm not sure about setting specific versions for vara commit itself

2022-11-22 10:40 UTC, NikVolf commented
@breathx feel free to update those, this is not an actual PR :)

2023-02-09 11:22 UTC, ukint-vs approved these changes

2023-02-09 11:36 UTC, breathx approved these changes

2023-02-09 11:37 UTC, merged