Add gas and value to tx fee
gear-tech/gear pull request #1944
Opened 2022-12-05 09:20 UTC by techraed

Continuation of the #1778 .

The rationale for this is to tell to `gear` users more about their expenses when calling `send_message`, `upload_program`, `create_program`, `send_reply`. More precisely, add gas and value info to current fees, so users won't be mistaken by expecting the call to be executed successfully.    

@gear-tech/dev

2022-12-05 09:40 UTC, SabaunT reviewed
Need to decide whether changes in `query_fee_details` are necessary.
From one side it's hard to include gas and value info to the details data, because we can break compatibility with the front-end (`polkadot-js/apps`) in the future, i.e. we don't know whether parity have plans to use this call internally somewhere.
From the other side, it's an available rpc call, so proper information must be given. Also I didn't find any internal usage of the `query_fee_details` right now in `polkadot-js/apps`.

What do you think? @breathx @ekovalev @shamilsan @gshep

2022-12-06 02:13 UTC, breathx approved these changes

2022-12-07 13:26 UTC, gshep requested changes
Looks good :+1:  but some changes are required.

As far as I understand there are no disagreements with this PR for improvements of user experience (@ekovalev ?). So I would like to see `TryExtract` & `MessageResources...` there and point the merge request to the main branch.

Then we could search for some consensus on #1937  independently.

2022-12-07 19:04 UTC, SabaunT commented
After some internal discussions we decided to close it

2022-12-07 19:04 UTC, closed without merging