feat(gcore): introduce `read_unchecked` from `read`
gear-tech/gear pull request #1983
Opened 2022-12-15 09:23 UTC by clearloop

Resolves #1859 

- add `gr_read_unchecked` based on `gr_read`
- export `gr_read_unchecked` to `gcore`

@gear-tech/dev

2022-12-18 16:44 UTC, breathx requested changes

2022-12-18 16:44 UTC, breathx commented on core-backend/sandbox/src/funcs.rs
> +    pub fn read_unchecked(ctx: &mut Runtime<E>, args: &[Value]) -> SyscallOutput {
we don't need separate syscall for this
use already existing one by playing around value of "resulting" ptr arg: if u32::MAX than mean as infallible

2022-12-26 10:54 UTC, shamilsan commented
I don't see `gr_read_unchecked` in this PR. Maybe it is worth changing PR's title and description?

2022-12-27 06:36 UTC, SabaunT approved these changes
lgtm, but would wait for @breathx review

2023-01-05 11:37 UTC, breathx requested changes
It's okay with gcore, but such fn required in gstd also
Going further, where is following changes for backend to ignore errors if error_len ptr is u32::MAX?

2023-01-09 09:08 UTC, breathx requested changes

2023-01-10 14:00 UTC, breathx requested changes

2023-01-23 11:12 UTC, breathx commented
#2083 merged, to be rebased and refactored as discussed personally

2023-02-20 17:13 UTC, closed without merging