Refactor core-backend errors
gear-tech/gear pull request #2138
Opened 2023-01-25 19:41 UTC by ark0f

The second step to the #1083, #1084

Based on and blocked by #2121

2023-01-31 08:42 UTC, gshep approved these changes
Awesome work! 💯

2023-01-31 08:42 UTC, gshep commented on core-backend/common/src/lib.rs
> +pub enum EnvironmentExecutionError<B, P> {
I personally prefer more longer names for generics

2023-01-31 08:42 UTC, gshep commented on core-backend/common/src/mock.rs
> +        todo!()
maybe `unimplemented!` is better since we don't intend to implement it ever

2023-01-31 11:07 UTC, breathx requested changes

2023-01-31 11:07 UTC, breathx commented on core-processor/src/ext.rs
> +        let value = self
```suggestion
        let res = self
```

2023-01-31 11:07 UTC, breathx commented on examples/binaries/syscall-error/src/lib.rs
> +        let mut len = MaybeUninit::uninit();
mv maybeuninint to buf, rm from len

2023-01-31 11:07 UTC, breathx commented on gsys/src/lib.rs
> +    /// - `len`: `mut ptr` for `u32` error length.
```suggestion
    /// - `len`: `mut ptr` for `u32` current error length.
```

2023-01-31 11:07 UTC, breathx commented on gsys/src/lib.rs
> +    /// - `buf`: `mut ptr` for buffer to store requested data.
```suggestion
    /// - `buf`: `mut ptr` for buffer to store previously occurred error.
```

2023-01-31 11:07 UTC, breathx commented on pallets/gear/src/benchmarking/syscalls.rs
>      pub fn gr_error(r: u32) -> Result<Exec<T>, &'static str> {
Re-review bench values

2023-01-31 13:56 UTC, ark0f commented on core-backend/sandbox/src/env.rs
> +use alloc::{collections::BTreeSet, string::ToString};
Should be refactored though whole project. Area of work is not for this PR

2023-01-31 19:47 UTC, ark0f commented on core-backend/wasmi/src/funcs/internal.rs
>              // TODO #1979
Will be done later

2023-02-01 11:50 UTC, shamilsan commented on core-backend/common/src/lib.rs
> +// '__gear_stack_end' export is inserted in wasm-proc or wasm-builder
```suggestion
// '__gear_stack_end' export is inserted by wasm-proc or wasm-builder
```

2023-02-01 12:42 UTC, breathx approved these changes

2023-02-01 12:42 UTC, breathx commented on core-backend/common/src/lib.rs
> +pub type EnvironmentExecutionResult<T, Env, EP> = Result<
separate aliases

2023-02-01 12:42 UTC, breathx commented on core-backend/sandbox/src/lib.rs
> +extern crate core;
rm extern core

2023-02-01 12:43 UTC, breathx commented on core-backend/common/src/lib.rs
> +        }
Seems original code is more readable
No performance boost, profit in 4 lines doesn't cover cons

2023-02-01 12:50 UTC, breathx commented on pallets/gear/src/benchmarking/syscalls.rs
>      pub fn gr_error(r: u32) -> Result<Exec<T>, &'static str> {
Discussed how to fix it

2023-02-01 15:16 UTC, merged