Fix backend errors handling for fallible syscalls
gear-tech/gear pull request #2176
Opened 2023-02-03 12:37 UTC by breathx

## Error explanation
For example let's take fallible `gr_unreserve_gas` syscall.
https://github.com/gear-tech/gear/blob/9d96bec693b34db229598d0e638502228dc1a43d/core-backend/sandbox/src/funcs.rs#L856-L871
For case if we failed to read read reservation id, atm we are leaving backend with wasm trap, while it should try write ext error about incorrect `reservation_id_ptr` to `write_err_unreserved`, because syscall supposed to be fallible and dance around results.
For case when fails write to `err_<something>` ptr, we already cannot parse error in user space so we should leave with a trap.

## TODO list
- [ ] Apply similar changes to wasmi backend
- [ ] Provide tests and check that it fails on master

2023-02-03 14:41 UTC, ark0f approved these changes

2023-02-03 15:50 UTC, grishasobol approved these changes

2023-02-03 15:50 UTC, grishasobol commented on core-backend/sandbox/src/runtime.rs
> +        let body_res = body_res;
Can you clarify this line please?

2023-02-03 18:28 UTC, grishasobol requested changes
We make everywhere : 
```rust
ctx.run_fallible(
|ctx| {
    let write_obj = ctx.register_write_as(T)
},
|ctx| {
    // main logic
},
|ctx, write_obj, res| {
    ctx.write_as(write_obj, T::from(res))
},
```

We can make generic method `run_fallible` with T param

2023-02-06 14:02 UTC, ark0f approved these changes

2023-02-06 14:02 UTC, ark0f commented on examples/binaries/backend-error/src/lib.rs
> +        assert!(res.length != 0)
Also read error to see it's correct

2023-02-06 14:02 UTC, ark0f commented on gsys/src/lib.rs
> +pub struct LengthBytes([u8; size_of::<Length>()]);
```suggestion
pub struct LengthBytes([u8; mem::size_of::<Length>()]);
```

2023-02-06 15:27 UTC, grishasobol approved these changes

2023-02-06 20:08 UTC, merged