Store only first missing block in scheduler
gear-tech/gear pull request #2404
Opened 2023-03-15 16:13 UTC by ark0f

Resolves #1333

2023-03-26 17:11 UTC, breathx requested changes
Migrations are must have here, so I'd switch atm on #2303 and merge it once mentioned one got solved

2023-03-26 17:11 UTC, breathx commented on common/src/scheduler/mod.rs
> +    type FirstMissingBlock: ValueStorage<Value = Self::BlockNumber>;
I'd rename it into something like `BlockPtr` or `BlockIterationHead`, cause it represents not necessary "missed" blocks

2023-03-26 17:11 UTC, breathx commented on common/src/scheduler/mod.rs
> +    /// The first block number, which have already passed,
adapt comment as well, this var may contain the latest bn if we go up to date

2023-03-26 17:11 UTC, breathx commented on common/src/scheduler/mod.rs
> +    /// Extra reserve for being able to pay for the first missing block.
revert comment, it was correct but got killed by your Cmd+F xd

2023-03-26 17:11 UTC, breathx commented on pallets/gear-scheduler/src/lib.rs
> +    type FirstMissingBlock<T> = StorageValue<_, BlockNumberFor<T>>;
Rename as well and note that this PR will require database migrations.
Let's train it within the task!

2023-03-26 17:11 UTC, breathx commented on common/src/scheduler/mod.rs
> +    type FirstMissingBlock: ValueStorage<Value = Self::BlockNumber>;
UPD: we keep it with None if we go up-to-date, but anyway current naming seems misleading for me

2023-04-25 14:01 UTC, breathx requested changes
case:
block N contains no tasks, first missed block = None
block N+1 contains tasks, but block producer missed run_queue extrinsic or runtime upgrade occurs 
block N+2 contains tasks and starts execute them because missed blocks = None so tasks from block N+1 lost forever

2023-05-03 11:08 UTC, grishasobol commented on pallets/gear/src/tests.rs
> +        assert!(!TaskPoolOf::<Test>::contains(&(N + 1), &task));
Where did you check that task has been processed successfully?

2023-05-09 14:09 UTC, breathx approved these changes

2023-05-10 18:39 UTC, shamilsan commented
@ark0f Are we ready to merge this brilliant PR?

2023-05-15 05:29 UTC, breathx commented
@ark0f merge master, please, and lets merge it

2023-05-15 17:24 UTC, merged