feat(gsdk): introduce proc-macro for generating short storage queries
gear-tech/gear pull request #2604
Opened 2023-05-01 10:01 UTC by clearloop

Resolves #2484 

introduced proc-macro `short`

```rust
/// imdocs at specified block.
#[short]
pub async fn storage_query_at(&self, a: T, block_hash: Option<H256>) -> R {
  // ...
}

// ----> will generate

/// imdocs
pub async fn storage_query(&self, a: T) -> R {
  self.storage_query_at(a, None).await
}
```

@gear-tech/dev

2023-05-01 13:16 UTC, breathx commented
Can we do it this way:
```rust
/// DOCS.
#[short]
pub async fn storage_query_at(&self, a: T, block_hash: Option<H256>) -> R { / .. / }

// ----
// EXPANDS INTO
// ----


async fn _storage_query_at(&self, a: T, block_hash: Option<H256>) -> R { / .. / }

/// DOCS
pub async fn storage_query(&self, a: T) -> R {
    _storage_query_at(None).await
}

/// DOCS as specific block_hash
pub async fn storage_query(&self, a: T, block_hash: H256) -> R {
    _storage_query_at(Some(block_hash)).await
}
```
See no reason to keep Option field in `*_at` fns

2023-05-02 09:14 UTC, DennisInSky commented
I do not quite like the macro name. It lacks of being descriptive enough. What do you think about `storage_read_func` or `storage_read_func_essence` denoting that this is a piece of code used for generating storage access funcs?

2023-05-02 09:17 UTC, DennisInSky commented
Another confusing thing wrt to naming is the `derive` in the name of the macro crate. As they say here https://doc.rust-lang.org/rust-by-example/trait/derive.html the Derive is about some trait implementation where you say which trait one wants implemented

2023-05-02 10:17 UTC, DennisInSky commented
> I do not quite like the macro name. It lacks of being descriptive enough. What do you think about `storage_read_func` or `storage_read_func_essence` denoting that this is a piece of code used for generating storage access funcs?

Maybe something like `read_storage_func_body` will be the most appropriate

2023-05-02 11:46 UTC, DennisInSky commented
> > Maybe something like `read_storage_func_body` will be the most appropriate
> 
> but this macro does not just generate a body, but functions with different usages, mark the generated functions' usage(s) make more sense tbh
> 
> since `fetch_at` means fetch storage at block, `fetch` means fetch storage from full blocks, so the full path of this macro could be `gsdk_codegen::storage::fetch_full`
> 
> or just mark `storage_fetch` and the docs will show the details

My understanding that this macro usage is more like an attribute especially in variant suggested by @breathx, i.e. with that macro one says "this is how I want data to be fetched, please generate proper set of funcs based on this"

2023-05-02 11:52 UTC, breathx requested changes

2023-05-02 11:52 UTC, breathx commented on gsdk/Cargo.toml
> +gsdk-codegen = { path = "./codegen" }
```suggestion
gsdk-codegen = { path = "codegen" }
```

2023-05-02 11:52 UTC, breathx commented on gsdk/codegen/Cargo.toml
> +edition = "2021"
```suggestion
[package]
name = "gsdk-codegen"
version = "0.1.0"
authors = ["Gear Technologies"]
edition = "2021"
license = "GPL-3.0"
```

2023-05-02 11:52 UTC, breathx commented on gsdk/codegen/src/lib.rs
> +/// Builds fn `query_storage_at` to
I'd add code sample from our GitHub conversation here

2023-05-02 11:52 UTC, breathx commented on gsdk/codegen/src/storage.rs
> +        short.attrs.iter_mut().find_map(|attr| {
Seems `find_map` usage is incorrect here. Try using `for_each`

2023-05-02 11:52 UTC, breathx commented on gsdk/codegen/src/storage.rs
> +            short.sig.ident.to_string().trim_end_matches(FULL_SUFFIX),
Don't we want to add some validation here for ident that it end with `_at` ? Same for comment and args

2023-05-02 11:52 UTC, breathx commented on gsdk/codegen/src/storage.rs
> +        let (at, full) = (self.0.clone(), self.full());
I'd request to write original signature using Option<H256> and placing into impl within macro expand

2023-05-02 16:29 UTC, DennisInSky commented on gsdk/codegen/src/storage.rs
> +    fn full(&self) -> ItemFn {
`at_latest`, `latest` works fine to my pov

2023-05-03 11:43 UTC, ark0f commented
I noticed that your changes have resulted in an increase of 300 lines, which seems excessive for one-time boilerplate. Can you please help me to understand reasons behind these changes?

2023-05-09 10:18 UTC, NikVolf commented
@breathx can you re-review?

2023-05-16 14:24 UTC, merged