feat(gclient): introduce module error
gear-tech/gear pull request #2638
Opened 2023-05-10 06:56 UTC by clearloop

Resolves #2372 

- Introduce ModuleError in gsdk from metadata
- Add ModuleError to gclient

Example

```rust
use crate::{
    errors::{self, ModuleError},
    Error,
};
use subxt::{
    error::{DispatchError, ModuleError as SubxtModuleError, ModuleErrorData},
    Error as SubxtError,
};

let error: GClientError = SubxtError::Runtime(DispatchError::Module(SubxtModuleError {
    error_data: ModuleErrorData {
        pallet_index: 14,
        error: [3, 0, 0, 0],
    },
    description: vec![],
    pallet: "".into(),
    error: "".into(),
})).into();

assert!(matches!(
    error,
    Error::Module(ModuleError::Treasury(
        errors::Treasury::InsufficientPermission
    ))
));
```

@gear-tech/dev 

I assume `match` is the main usage of handling module errors for now, if need to handle `Eq`, I can add methods for `ModuleError` as well

```rust
let t: ModuleError = <error>;
assert_eq!(
    t.as_treasury(),
    Some(...)
);
```

cc @fluiderson

2023-05-15 09:25 UTC, fluiderson approved these changes

2023-05-15 09:38 UTC, breathx requested changes
Please add test for initial issue in gclient

2023-05-15 09:38 UTC, breathx commented on Cargo.lock
>  name = "aead"
I'd avoid spontaneous `cargo update`s

2023-05-15 09:38 UTC, breathx commented on gclient/src/lib.rs
> +pub use gsdk::metadata::errors;
I'd export error directly

2023-05-15 09:38 UTC, breathx commented on gsdk/src/metadata/errors.rs
> +export_module_error! {
Can we somehow go with discriminant safety?
`construct_runtime` doesn't support anything except literals, but may there by some workaround?

2023-05-15 09:38 UTC, breathx commented on gsdk/src/metadata/mod.rs
> +pub static PALLETS: [&str; 24usize] = [
redundant code?

2023-05-15 09:38 UTC, breathx requested changes
Please add test for initial issue in gclient

2023-05-17 06:06 UTC, breathx commented
> > Please add test for initial issue in gclient
> 
> do you mean
> 
> https://github.com/gear-tech/gear/pull/2638/files#diff-f4ffc8e354b16f29a85b2f4347c3cd82a833eb2c79cc0221c54d2f51c277438aR156
> 
> or adding test same as https://github.com/gear-dapps/supply-chain/blob/790957b5e7c2eabef87ffe1d58c6d994f4bbe0b6/deploy/src/lib.rs#L46-L57, but both the issue and this pr are not for testing the functionality of the API but parsing the errors

Second option. Just to demonstrate for ecosystem how to parse the errors

2023-05-20 07:30 UTC, breathx approved these changes

2023-05-30 11:31 UTC, merged