feat(core): add `gr_cost` syscall
gear-tech/gear pull request #2691
Opened 2023-05-30 06:04 UTC by tltsutltsu

Resolves #2637.

- [x] add syscall
- [ ] add example to test that syscall works
- [ ] switch to enum input for syscall?
- [ ] update weights

2023-06-06 06:41 UTC, breathx requested changes
syscall(i32) -> ptr err_len (u32 bytes) + cost (u128 bytes)

2023-06-12 13:04 UTC, NikVolf requested changes
please use ids instead of strings in ffi

2023-06-19 16:41 UTC, StackOverflowExcept1on commented
Did you forget about `core-backend/wasmi/src/funcs_tree.rs`?

2023-06-27 19:42 UTC, breathx requested changes

2023-06-27 19:42 UTC, breathx commented on core-backend/common/src/funcs.rs
> +        cost_name_ptr: u32,
what is these names etc?
just match num -> cost type

2023-07-12 15:13 UTC, breathx commented
To be reopened once work started again

2023-07-12 15:13 UTC, closed without merging