feat!: Add ability to deposit gas for reply handling.
gear-tech/gear pull request #2725
Opened 2023-06-05 19:39 UTC by breathx

2023-06-06 07:39 UTC, gshep approved these changes
LGTM! :+1:

2023-06-06 07:39 UTC, gshep commented on gcore/src/exec.rs
> +/// deposit - the only it wil be used for execution of `handle_reply`.
```suggestion
/// deposit - the only it will be used for execution of `handle_reply`.
```

2023-06-06 07:39 UTC, gshep commented on gstd/src/exec.rs
> +/// deposit - the only it wil be used for execution of `handle_reply`.
```suggestion
/// deposit - the only it will be used for execution of `handle_reply`.
```

2023-06-06 14:33 UTC, SabaunT requested changes

2023-06-06 14:33 UTC, SabaunT commented on core-processor/src/ext.rs
> +        self.charge_gas_if_enough(amount)?;
shouldn't we `reduce` instead of `burn`? The `amount` will be re-used for the other message.

2023-06-06 15:05 UTC, ark0f commented on pallets/gear/src/benchmarking/syscalls.rs
> +            imported_functions: vec![SysCallName::ReplyDeposit, SysCallName::Send],
Add comment `gr_send` is required to populate `message_context.outcome.handle` so `gr_reply_deposit` can be called

2023-06-06 15:22 UTC, breathx commented on core-errors/src/lib.rs
> +    IncorrectMessageForReplyDeposit = 4,
I can't see any other errors for future with the reply deposits now
It's not exactly message error, cause within the call that propagates such errors we don't sent message, we operate with message id already sent. DuplicateReply is when you try to send second reply. DuplicateReplyDeposit is when you try to create deposit for any message's future reply twice

2023-06-07 17:53 UTC, grishasobol commented on runtime/gear/src/weights/pallet_gear.rs
> +    fn gr_reply_deposit(r: u32, ) -> Weight {
My respect for diff only for new one syscall.

2023-06-11 06:52 UTC, breathx commented on pallets/gear/src/manager/journal.rs
> +        log::debug!("Creating reply deposit {amount} gas for message id {future_reply_id}");
Its better than to go through all logs in pallets because that's not the only one place with debug

2023-06-11 06:53 UTC, breathx commented on examples/binaries/fungible-token/demo_fungible_token.meta.txt
metafile of demo. no idea why it wasn't on master. maybe author gitignored it locally

2023-06-11 08:17 UTC, merged