Fix reserve-use-unreserve panic
gear-tech/gear pull request #2772
Opened 2023-06-14 11:40 UTC by ark0f

Resolves gear-tech/core-audit#24

2023-06-14 11:52 UTC, NikVolf approved these changes

2023-06-14 13:03 UTC, SabaunT approved these changes

2023-06-14 13:12 UTC, breathx approved these changes

2023-06-15 03:15 UTC, grishasobol requested changes
Please set label `A0-pleasereview`

2023-06-15 04:12 UTC, grishasobol approved these changes

2023-06-15 07:48 UTC, merged