Remove unused `CountersOwner::refund_gas`
gear-tech/gear pull request #2776
Opened 2023-06-14 14:16 UTC by SabaunT

2023-06-14 14:37 UTC, shamilsan commented on core-processor/src/ext.rs
> +        // This statement is like an op that increases `"eft" counter, but do not affect "burned" counter,
`left`?
```suggestion
        // This statement is like an op that increases "left" counter but does not affect "burned" counter,
```

2023-06-14 14:39 UTC, shamilsan approved these changes

2023-06-14 14:48 UTC, SabaunT commented on core-processor/src/ext.rs
> +        // This statement is like an op that increases `"eft" counter, but do not affect "burned" counter,
fixed

2023-06-14 14:55 UTC, grishasobol approved these changes

2023-06-15 03:13 UTC, grishasobol requested changes
Please set label `A0-pleasereview`

2023-06-15 03:25 UTC, grishasobol requested changes
Conventional Commits

2023-06-15 08:48 UTC, grishasobol approved these changes

2023-06-15 09:03 UTC, merged