perf(wasm-builder): parse `Cargo.toml` before remapping path
gear-tech/gear pull request #2902
Opened 2023-07-04 15:32 UTC by StackOverflowExcept1on

2023-07-04 17:32 UTC, DennisInSky commented on utils/wasm-builder/src/lib.rs
> +    fn need_remap_path(&self, enabled_features: &[String]) -> bool {
```suggestion
    fn need_path_remap(&self, enabled_features: &[String]) -> bool {
```

2023-07-04 17:36 UTC, DennisInSky commented on utils/wasm-builder/src/lib.rs
> +        });
Could it be the `debug` feature is enabled via a transitive dependency like
`dapp` crate depends on some `dapp-lib` crate which in turn depends on `gstd` with the `debug` feature on

2023-07-04 17:38 UTC, DennisInSky commented on utils/wasm-builder/src/wasm_project.rs
> +    /// Return the path to the temporary generated `Cargo.toml`.
The comment has been copy-pasted from the below method

2023-07-04 18:13 UTC, DennisInSky commented on utils/wasm-builder/src/lib.rs
> +            .flatten()
Btw, there is the same question about transitive features

2023-07-12 15:33 UTC, breathx requested changes
Apply fixes for @DennisInSky comments

2023-07-12 16:44 UTC, StackOverflowExcept1on commented
@breathx #2915 will add a panic handler feature to gstd. It makes sense to enable path remapping only when the panic handler is enabled.

If the user uses dependency (such as dapps-gear-lib) that references gstd, the user should disable the panic handler. Otherwise, such dependency will define the panic handler twice, and we will consider it semantically incorrect (also it leads to compile error).

Does it make sense to check transitive dependencies for the `gstd/debug` function in this case?

2023-07-13 09:20 UTC, DennisInSky commented on utils/wasm-builder/src/lib.rs
> +        if env::var("__GEAR_WASM_BUILDER_NO_PATH_REMAP").is_err() && profile == "production" {
This more resembles exlicit feature and has less flexibility then a dedicated feature. If it is the only option we can suggest to our customers, I would suggest introducing the latter, so they can decide themselves whether and when they want the paths to be remapped.

2023-07-15 15:43 UTC, breathx approved these changes

2023-07-17 08:29 UTC, DennisInSky approved these changes

2023-07-17 08:30 UTC, merged