test(core): signals tests
gear-tech/gear pull request #2986
Opened 2023-07-26 17:05 UTC by tltsutltsu

Resolves: #2846

@gear-tech/dev

2023-08-06 11:29 UTC, breathx requested changes
Please write somewhere docs for each case and ref tests that we covered all of them
Start with general cases and extend with their subcases (e.g. panic case: oom, out of gas, anything else ... )

2023-08-06 11:29 UTC, breathx commented on examples/signal-entry/src/lib.rs
> +                    msg::send(unsafe { INITIATOR }, b"handle_signal_equal", 0).unwrap();
isn't true/false sending easier?

2023-08-06 11:29 UTC, breathx commented on pallets/gear/src/tests.rs
> +            run_to_block(2, None);
assert program is active and initialised

2023-08-06 11:29 UTC, breathx commented on pallets/gear/src/tests.rs
> +            assert!(GasHandlerOf::<Test>::get_system_reserve(mid).is_err());
assert it exists before

2023-08-07 17:25 UTC, StackOverflowExcept1on commented
Something wrong happen with branch. Github shows +-5000 lines changed in this PR.

2023-08-28 15:44 UTC, breathx commented
Awesome doc

2023-08-28 18:31 UTC, clearloop approved these changes

2023-08-29 08:58 UTC, tltsutltsu commented on core-errors/signal-code-testing.md
> +    This case is quite tricky to test, because accurately predicting the amount of gas consumed during program execution and estimating gas usage upon memory access can be difficult. As a result, the
that's a good way, thanks!

2023-08-30 05:01 UTC, merged