Adding docs to gcore and minor refactoring of syscalls
gear-tech/gear pull request #303
Opened 2021-09-28 14:10 UTC by peter-cmw

Added initial documentation draft to gcore modules
Remove send methods that do not send value
Return Message Id  from reply method

2021-09-28 14:24 UTC, NikVolf commented on gcore/src/exec.rs
> +//! Sys calls related to smart contract execution.
```suggestion
//! Sys calls related to program execution flow.
```

2021-09-28 14:24 UTC, NikVolf commented
We should avoid notion of "smart contracts"

Those are "programs"

(there are multiple issues about that in the pr)

2021-09-28 14:47 UTC, NikVolf commented on gcore/src/exec.rs
> +//! Provides api for low-level async implementation (probably gas should be other mod)
```suggestion
//! Provides api for low-level async implementation
```

2021-09-28 15:21 UTC, NikVolf approved these changes

2021-09-29 10:35 UTC, shamilsan requested changes
Please don't merge now, I'll fix typos and merge it.

2021-09-29 10:35 UTC, shamilsan commented on gcore/src/exec.rs
> +/// // Perform work while gas_available is more then 1000
```suggestion
/// // Perform work while gas_available is more than 1000
```

2021-09-29 18:09 UTC, merged