perf(lazy-pages,runtime-interface): memory usage, avoid calculations
gear-tech/gear pull request #3193
Opened 2023-08-28 12:06 UTC by ukint-vs

Resolves # .

-
-
-

@reviewer-or-team

2023-08-31 14:05 UTC, breathx approved these changes

2023-09-20 14:44 UTC, NikVolf commented
rebase to master and request Validator testing?

2023-09-20 15:00 UTC, ukint-vs commented
> rebase to master and request Validator testing?

it's not done. The weight of per-byte becnhes has been increased. Iterators need to be profiled or removed.

2023-10-10 08:02 UTC, ukint-vs commented on runtime-interface/src/lib.rs
> +            &mut reads.iter().cloned(),
it's deprecated api.

2023-10-15 10:05 UTC, breathx requested changes

2023-10-15 10:05 UTC, breathx commented on lazy-pages/src/host_func.rs
> +    reads: &mut (impl Iterator<Item = MemoryInterval> + std::fmt::Debug),
Why should `Debug` appear here?

2023-10-15 10:05 UTC, breathx commented on lazy-pages/src/host_func.rs
> +    current_pages: Option<RangeInclusive<u32>>,
why isn't it btreeset?

2023-10-15 10:05 UTC, breathx commented on lazy-pages/src/host_func.rs
> +    current_pages: Option<RangeInclusive<u32>>,
or anything else

2023-10-15 10:05 UTC, breathx commented on lazy-pages/src/host_func.rs
> +    intervals: &mut impl Iterator<Item = MemoryInterval>,
why should they be mutable?

2023-11-10 11:23 UTC, breathx commented
Please reopen once work will be continued

2023-11-10 11:23 UTC, closed without merging