feat(pallet-gear-rpc): read states in batch
gear-tech/gear pull request #3208
Opened 2023-09-02 18:09 UTC by ukint-vs

By this call rpc callee can avoid network bottleneck by reading states in one iteration.

This is useful for indexers or for example to fetch all nft contracts.

Usage:
```bash
❯ curl -s -H "Content-Type: application/json" -d '{
   "id":1,
   "jsonrpc":"2.0",
   "method":"gear_readStateBatch",
   "params":[
      [
         [
            "0x6f3abd2d1c8d71812eefdda68228bdf80053ca6549d8b13897a671a8580e9d64",
            "0x00"
         ],
         [
            "0x6f3abd2d1c8d71812eefdda68228bdf80053ca6549d8b13897a671a8580e9d64",
            "0x00"
         ]
      ]
   ]
} http://127.0.0.1:9944

{
   "jsonrpc":"2.0",
   "result":[
      "0x0026c7026331ed7e90eb5a6fad656c910839182d8fabd77a4bcd6a62b7b0fb967a00000c616161107777777700000000000000000000000000000000000000000000000000000000000000000426c7026331ed7e90eb5a6fad656c910839182d8fabd77a4bcd6a62b7b0fb967a000000",
      "0x0026c7026331ed7e90eb5a6fad656c910839182d8fabd77a4bcd6a62b7b0fb967a00000c616161107777777700000000000000000000000000000000000000000000000000000000000000000426c7026331ed7e90eb5a6fad656c910839182d8fabd77a4bcd6a62b7b0fb967a000000"
   ],
   "id":1
}
```

todo:

- [ ] find a way to run it in one copy (collect results)

@reviewer-or-team

2023-09-03 11:58 UTC, breathx requested changes
Except security issue in comment, lgtm!

2023-09-03 11:58 UTC, breathx commented on pallets/gear/rpc/src/lib.rs
> +        batch_id_payload: Vec<(H256, Bytes)>,
Opened an issue to max this usage safe as well #3210.
At this moment I'd hardcode some const

2023-09-05 13:47 UTC, breathx approved these changes

2023-09-05 14:08 UTC, shamilsan approved these changes
Very useful RPC 🔥

2023-09-05 14:29 UTC, merged