feat(vara): Store dust in treasury
gear-tech/gear pull request #3364
Opened 2023-09-26 20:20 UTC by ukint-vs

Dust will move into treasury pot.

@reviewer-or-team

2023-09-27 10:03 UTC, breathx requested changes
Any test?

2023-09-27 10:44 UTC, ekovalev approved these changes

2023-10-02 19:17 UTC, breathx approved these changes

2023-10-02 19:17 UTC, breathx commented on runtime/vara/src/integration_tests.rs
> +    Treasury::on_initialize(current_blk);
```suggestion
    Treasury::on_finalize(current_blk);
```

2023-10-02 19:17 UTC, breathx commented on runtime/vara/src/integration_tests.rs
> +    Treasury::on_initialize(current_blk);
and keep pallets ordering pls

2023-10-11 12:34 UTC, breathx requested changes
Please move dust into offset pool

2023-10-13 10:25 UTC, closed without merging