feat(pallet-gear): Added example and test to test signal weak case
gear-tech/gear pull request #3421
Opened 2023-10-18 12:13 UTC by mqxf

Resolves #2814 

@reviewer-or-team

2023-10-18 14:04 UTC, StackOverflowExcept1on commented on examples/signal-wait/src/wasm.rs
> +        gstd::exec::system_reserve_gas(1_000_000_000).unwrap();
```suggestion
        exec::system_reserve_gas(1_000_000_000).unwrap();
```

2023-10-25 14:03 UTC, SabaunT reviewed
lgtm, but I'd re-write demo using `demo-constructor`. @breathx could you please check the test itself?

2023-10-29 18:41 UTC, breathx requested changes

2023-10-29 18:41 UTC, breathx commented on pallets/gear/src/tests.rs
> +        assert!(WaitlistOf::<Test>::contains(&pid, &signal_mid));
so whats the aim of the test?
its in checking that everything works well when signal_mid ends up in waitlist as outdated, so you need prolong test

2023-10-29 18:42 UTC, breathx commented
> lgtm, but I re-write demo using `demo-constructor`. @breathx could you please check the test itself?

yep, demo can be rewritten with demo_constructor

2023-11-01 13:59 UTC, mqxf commented
The test should be correct, going to rewrite using demo-constructor

2023-11-10 11:25 UTC, breathx approved these changes

2023-11-10 11:26 UTC, breathx requested changes
Whats happening with the diff?

2023-11-12 11:50 UTC, mqxf commented
The diff was breaking because of changes in master I assume.  I just merged master into this and its back to normal

2023-11-14 20:51 UTC, breathx requested changes

2023-11-14 20:51 UTC, breathx commented on pallets/gear/src/tests.rs
> +fn test_handle_signal_wait_old() {
merge initial version with this pr, please
in several - adapt it to constructor

2023-11-19 11:34 UTC, breathx approved these changes

2023-11-19 11:34 UTC, breathx commented
@SabaunT ptal

2023-11-27 07:40 UTC, SabaunT approved these changes

2023-11-27 09:41 UTC, merged