refactor(wasm-instrument, wasm-gen): Make syscalls errors config and syscalls results processing more consistent
gear-tech/gear pull request #3554
Opened 2023-11-30 18:25 UTC by SabaunT

- [ ] Make it impossible to set infallible syscalls to syscalls errors config
- [ ] Introduce on type level those guarantees that are required for `build_result_processing*` functions.

2023-12-04 17:42 UTC, mertwole requested changes

2023-12-04 18:15 UTC, StackOverflowExcept1on commented on utils/wasm-gen/src/generator/syscalls/invocator.rs
> +                    panic!("Incorrect last parameter type: expected pointer");
I'd use `let-else` here
```rust
let Some(res_ptr) = param_setters
    .last()
    .expect("At least one argument in fallible syscall")
    .as_i32()
else {
    panic!("Incorrect last parameter type: expected pointer");
};

vec![...]
```

2023-12-05 14:25 UTC, SabaunT commented on utils/wasm-instrument/src/syscalls.rs
> +    pub enum Ptr {
as we discussed, it makes more sense to remove `PtrField` rather than `Mut...` variants as `ErrPtrs` are all mutable

2023-12-05 14:28 UTC, SabaunT commented on utils/wasm-gen/src/config/syscalls/process_errors.rs
> +    pub fn contains(&self, syscall: InvocableSyscall) -> bool {
It's given to user API, must be public anyway.

2023-12-05 14:47 UTC, SabaunT commented on utils/wasm-instrument/src/syscalls.rs
> +impl From<ParamType> for ValueType {
done

2023-12-05 14:47 UTC, SabaunT commented on utils/wasm-instrument/src/syscalls.rs
> +    /// There are only 2 syscalls returning error value: `Alloc`` and `Free`
done

2023-12-05 14:47 UTC, SabaunT commented on utils/wasm-gen/src/generator/syscalls/invocator.rs
> +    fn build_error_processing(
done

2023-12-05 14:47 UTC, SabaunT commented on utils/wasm-gen/src/generator/syscalls/invocator.rs
> +                // but return value indicating error. These are currently `Alloc` and `Free`.
done

2023-12-05 14:48 UTC, SabaunT commented on utils/wasm-instrument/src/syscalls.rs
> +    GrInfallible(InfallibleSyscallSignature),
done

2023-12-05 14:48 UTC, SabaunT commented on utils/wasm-gen/src/generator/syscalls/invocator.rs
> +                    panic!("Incorrect last parameter type: expected pointer");
done

2023-12-05 14:56 UTC, SabaunT commented on utils/wasm-instrument/src/syscalls.rs
> +impl From<ParamType> for ValueType {
done

2023-12-05 14:56 UTC, SabaunT commented on utils/wasm-instrument/src/syscalls.rs
> +    pub enum Ptr {
done

2023-12-05 16:02 UTC, mertwole approved these changes

2023-12-05 16:36 UTC, StackOverflowExcept1on approved these changes

2023-12-11 15:17 UTC, breathx approved these changes
Avoiding diving into details, seems ok for me
The few design questions:
- don't we really can avoid duplicating variants like Ptr::Hash, Ptr::MutHash etc
- are we okay with such huge enum nesting of arguments while building syscall and so on?

2023-12-12 12:23 UTC, merged