feat(vara): Split fees 50/50, author/treasury
gear-tech/gear pull request #3652
Opened 2024-01-10 23:50 UTC by ukint-vs

Send 50% of fees to the block author and 50% to the treasury.

@reviewer-or-team

2024-01-11 05:07 UTC, gshep approved these changes

2024-01-11 05:07 UTC, gshep commented on runtime/common/src/lib.rs
> +            let mut split = fees.ration(50, 50);
i would rename to something like `let (mut to_author, to_treasury) = ...`

2024-01-11 05:07 UTC, gshep commented on runtime/common/src/lib.rs
> +            use pallet_treasury::Pallet as Treasury;
please place the import in the function start

2024-01-14 17:18 UTC, breathx requested changes
If I'm not mistaken, we were talking about gas fees, not tx-s (or not only tx-s).
And I'd make this constant customisable with governance not only on upgrades.

Furthermore, this question is still considering, so pls don't merge yet.

2024-02-06 09:23 UTC, breathx commented
Is it ready for review?

2024-02-06 20:19 UTC, ukint-vs commented
> Is it ready for review?

Not yet. Need final touches and tests

2024-02-12 07:55 UTC, breathx commented
Fix tests to pass CI pls @ukint-vs

2024-02-28 12:21 UTC, ukint-vs commented
@CodiumAI-Agent /review

2024-02-29 15:54 UTC, breathx commented
@ukint-vs still fails CI

2024-03-01 16:00 UTC, ukint-vs commented
> @ukint-vs still fails CI

Fixed. Set 100% to the block author

2024-03-06 22:09 UTC, breathx commented
To be reviewed soon.

Please consider to impl 3 different constants in code in some dedicated place, for example - runtime/common.
Percents from tx fees; percents from gas burned; percents from storage rent gas.

2024-04-08 11:35 UTC, breathx commented
According to @ukint-vs, WIP

2024-05-26 05:40 UTC, breathx commented
@ukint-vs pls finalise this one

2024-06-11 14:04 UTC, breathx requested changes
On gear bank side, please perform ratio multiplying only once before transfer
Otherwise, great done 👍🏻

2024-06-11 14:04 UTC, breathx commented on runtime/vara/src/integration_tests.rs
> +            DealWithFees::on_unbalanceds(vec![fee, tip].into_iter());
shouldn't the case be covered by pallet transaction payment?

2024-06-11 14:04 UTC, breathx commented on runtime/vara/src/lib.rs
> +    pub SplitGas: Option<(Perbill, AccountId)> = None;
please open todo to move this logic into pallet storage to be able to adjust the value by governance avoiding runtime upgrades

2024-07-07 15:32 UTC, breathx commented
Actualise branch and resolve opened discussions, please @ukint-vs

2024-08-16 18:32 UTC, breathx approved these changes

2024-08-16 18:32 UTC, breathx commented on pallets/gear-bank/src/lib.rs
> +            type SplitGas = SplitGas;
```suggestion
            type SplitGasFeeRatio = SplitGasFeeRatio;
```

2024-08-16 18:32 UTC, breathx commented on runtime/vara/src/integration_tests.rs
> +fn test_fees_and_tip_split() {
Test for gas would be awesome also

2024-08-21 13:39 UTC, ukint-vs commented on runtime/vara/src/integration_tests.rs
> +fn test_fees_and_tip_split() {
test case is in gear-bank tests

2024-08-22 14:51 UTC, merged