refactor(gtest): Remove ambiguous API and incorrectly named functions
gear-tech/gear pull request #3676
Opened 2024-01-19 13:22 UTC by mqxf

Resolves #3224

Previously, is_user, the only function, would return true is an actor was a `TestActor::User` OR if the ProgramId was not a valid actor. This caused some issues, like is_active_program, which would check if a program existed, would return true if a ProgramId didn't exist. I fixed this by removing that extra branch, now is_user tests only is the actor is `TestActor::User`. Aswell as that, I added is_program, which tests if it is `TestActor::Active` or `TestActor::Inactive`, and finally is_active_program.

@reviewer-or-team

2024-01-28 19:00 UTC, techraed approved these changes
seems ok, need final review from original author @breathx

2024-01-31 16:23 UTC, breathx requested changes

2024-01-31 16:23 UTC, breathx commented on gtest/src/manager.rs
This should still be refactored:
```rust
use TestActor::*;
matches!(x, Initialized(..), Uninitialized(..), Dormant) // is_program
matches!(x, Initialized(..), Uninitialized(..)) // is_active_program
matches!(x, Initialized(..)) // is_initialised_program
actors.get(id).is_none() || matches!(x, User) // is_user
```

2024-02-27 06:38 UTC, breathx approved these changes

2024-02-27 06:39 UTC, merged