chore: remove pallet::getter usage
gear-tech/gear pull request #3887
Opened 2024-04-15 03:38 UTC by playX18

2024-04-16 03:31 UTC, playX18 commented on pallets/gear-bank/src/lib.rs
> +        pub fn unused_value() -> BalanceOf<T> {
What should happen when these types are used outside? We should add `pub use pallet::BlockNumber` or `pub use pallet::Bank`? Another approach is replace with path usage like `gear_bank::pallet::Bank`

2024-04-16 10:13 UTC, breathx commented on pallets/gear-bank/src/lib.rs
> +        pub fn unused_value() -> BalanceOf<T> {
For case somebody needs access to pallets storage, the storage should be `pub type`, or just keep such wrappers as `impl Pallet<T>` fns.

Atm Im mostly about inlining them when nobody external doesnt depend on it

2024-04-17 02:15 UTC, playX18 commented on pallets/gear-bank/src/lib.rs
> +        pub fn unused_value() -> BalanceOf<T> {
Should be solved now

2024-04-24 18:00 UTC, ukint-vs requested changes
Please explain the purpose of removing these getters. Because each getter can be easily accessed by clients without having to manually calculate the storage key.

2024-04-24 18:00 UTC, ukint-vs commented on pallets/staking-rewards/src/lib.rs
> -    #[pallet::getter(fn ideal_staking_ratio)]
All storage values from this pallet are used in frontends and provide useful info. There's no point in keeping it private.

2024-04-25 14:58 UTC, ukint-vs approved these changes
discussed

2024-04-26 12:34 UTC, merged