feat: Update substrate v1.4.0
gear-tech/gear pull request #3934
Opened 2024-05-01 08:58 UTC by ukint-vs

Related changes:
- https://github.com/paritytech/polkadot-sdk/pull/1256
- https://github.com/paritytech/polkadot-sdk/pull/1189
- https://github.com/paritytech/polkadot-sdk/pull/2048
- https://github.com/paritytech/polkadot-sdk/pull/2099
- https://github.com/paritytech/substrate/pull/14405

@gear-tech/dev

2024-05-13 16:36 UTC, breathx commented
Please, rebase, cleanup and mention attached migrations in description

2024-05-16 17:35 UTC, breathx requested changes
Requesting changes just for avoiding misclick and merge
The PR requires @ekovalev's deep review

2024-05-17 13:47 UTC, ekovalev approved these changes
Great work. Authorship part looks cleaner than before.

2024-05-26 10:49 UTC, breathx approved these changes

2024-05-26 10:49 UTC, breathx commented on runtime/vara/src/lib.rs
> +    pub const MaxNominators: u32 = 512;
wouldn't this type of tx exceed our non-mandatory limits?
I think its better to keep 256 for both?

2024-05-26 10:49 UTC, breathx commented on node/authorship/src/tests.rs
> +    _backend: Arc<TestBackend>,
could be removed now?

2024-05-26 10:50 UTC, breathx commented
Well done!

Please, don't merge it atm to make sure smooth delivery. Also needs to resolve master branch conflicts and leave here a comment about CI migrations (I remember it was discussed personally, but better to post it)

2024-07-07 15:33 UTC, breathx commented
Actualise branch and resolve opened discussions, please @ukint-vs

2024-07-10 14:43 UTC, breathx approved these changes

2024-07-10 14:47 UTC, breathx commented on node/authorship/src/tests.rs
> +    _backend: Arc<TestBackend>,
to be solved by @ukint-vs in upcoming PR

2024-07-10 14:47 UTC, merged