chore: debug assert reservation states in process_success
gear-tech/gear pull request #3966
Opened 2024-05-16 10:22 UTC by playX18

@breathx

2024-05-16 14:15 UTC, breathx requested changes

2024-05-16 14:15 UTC, breathx commented on core-processor/src/processing.rs
> +            DispatchResultKind::Success => process_success(Success, res, Some(system_reservation_ctx)),
make assertion in place instead of impl new unused argument for pub fn

2024-05-17 16:52 UTC, breathx commented on core-processor/src/processing.rs
> +                if let (Some(current_prev), Some(current_res)) = (
couldn't matching and extraction be hidden in debug_assert to avoid excess code in prod compile?

2024-05-18 13:08 UTC, techraed commented on core-processor/src/processing.rs
> +                    debug_assert!(current_res <= current_prev);
I'd add an explanotary comment, as it seems you are asserting the invariant, aren't you?
also, maybe even have a separate match arm for variants, for which reservations must be checked. That could reduce copy-paste I guess

2024-05-26 06:48 UTC, breathx requested changes

2024-05-26 06:48 UTC, breathx commented on core-processor/src/processing.rs
> +                    debug_assert!(system_reservation_ctx
both these checks are aimed to verify system reservations
1. these checks aren't 100% correct
2. you need to check initial task's idea: amount of common reservations (not the amount of gas in system reservation)

2024-06-11 13:07 UTC, breathx commented
@playX18 why is it staling?

2024-07-10 14:18 UTC, breathx approved these changes

2024-07-10 14:18 UTC, breathx commented
@ark0f please take a look

2024-07-10 18:31 UTC, ark0f approved these changes

2024-07-10 18:53 UTC, techraed requested changes

2024-07-10 18:53 UTC, techraed commented on core-processor/src/processing.rs
> +                        .current_reservation
it's always `None`, why check it?

2024-07-10 18:53 UTC, techraed commented on core-processor/src/processing.rs
> +                            .map(|current| initial <= current))
that should be checked for being equal, because of the impementation details

2024-07-10 18:53 UTC, techraed commented on core-processor/src/processing.rs
> +                        .current_reservation
still if you want to check that, you must use `unwrap_or_default` for the `system_reservation_ctx.current_reservation` (the one created before execution)

2024-07-10 18:56 UTC, techraed commented on core-processor/src/processing.rs
> +                    // thus making initial reservation less than current one.
what you actually wrote here must be checked the different way:
1. take the `system_reservation_ctx.previous_reservation`
2. take the `res.system_reservation_ctx.previous_reservation + res.system_reservation_ctx.current_reservation`
3. check that the result of 2 >= result of 1

2024-07-10 19:03 UTC, techraed commented on core-processor/src/processing.rs
> +                    // thus making initial reservation less than current one.
maybe even instead of 2 use `res.context_store.system_reservation` as it already has the sum of 2

2024-07-11 14:30 UTC, techraed approved these changes
@ark0f re-check, please

2024-07-11 14:30 UTC, techraed commented on core-processor/src/processing.rs
> +                    ));*/
remove that please

2024-07-11 14:30 UTC, techraed commented on core-processor/src/processing.rs
> +                    ));*/
```suggestion
```

2024-07-30 19:26 UTC, ark0f approved these changes

2024-07-31 10:56 UTC, breathx approved these changes

2024-08-01 00:34 UTC, merged