feat(pallet_gear): Introduce invariant: all user non-reply messages go to mailbox.
gear-tech/gear pull request #4060
Opened 2024-07-16 11:48 UTC by techraed

All instant (no delay) user non-reply ("handle") messages are now sent to mailbox.  

Completely removes `safe_gasful_send` as it introduced some implicit risky invariants.

- All user messages now go to mailbox, except for reply messages (as it was before)
- The only exception is for delayed reservation messages, but that will be introduced in a separate PR
- Some comments on tests:
  1. `auto_reply_from_user_no_mailbox`, `delayed_send_user_message_payment`, `mailbox_sending_instant_transfer`
    Completely removed as there's no need in that - all user messages will be sent to mailbox (a separate PR for applying this on delayed case with reservations).
  2. Most of adjusted tests sent 0 gas limit withing `send_wgas` type syscalls. So a minimum of a mailbox threshold was given in all the cases.

2024-07-18 20:11 UTC, ark0f approved these changes

2024-07-18 20:11 UTC, ark0f commented on pallets/gear/src/tests.rs
> +        run_to_block(40, None);
It's better to calculate exact block

2024-07-19 13:28 UTC, techraed commented on core-processor/src/ext.rs
> +        cover_mailbox_threshold: bool,
discussed

2024-07-19 13:28 UTC, techraed commented on pallets/gear/src/tests.rs
> +        run_to_block(40, None);
done

2024-07-19 13:28 UTC, techraed commented on pallets/gear/src/tests.rs
> +        i64.const 3000  ;; gas limit
done

2024-07-19 13:32 UTC, techraed commented on Cargo.lock
done

2024-07-24 10:10 UTC, breathx requested changes
As far as I remember, it was discussed to impl the invariant in the way that every gasLESS messages sent to user requires MB threshold so further inserted in mailbox in case of user sending. At this point it applies for all messages, which is incorrect with initial idea. Furthermore, isn't the implementation panic when sends with gas = 1 to user? Seems like this.

2024-07-24 10:58 UTC, techraed commented
Discussed: the issue is that 0 gas limit for gasful messages is a legit case.

2024-07-29 14:13 UTC, techraed commented
@breathx ptal

2024-07-30 10:56 UTC, breathx requested changes

2024-07-30 10:56 UTC, breathx commented on core-processor/src/ext.rs
> +            DispatchKind::Init | DispatchKind::Reply => {
what if we create program from code_id and salt and code_id doesnt exist, so `store_new_programs` fails and this init message will be treated as user message, isn't it?

needs double checking how we handle it

2024-07-30 11:00 UTC, breathx commented on core-processor/src/ext.rs
> +            DispatchKind::Init | DispatchKind::Reply => {
discussed

2024-07-30 11:00 UTC, breathx approved these changes

2024-07-30 17:09 UTC, merged