feat(gtest): Implement send_signal and system gas reserve/unreserve
gear-tech/gear pull request #4075
Opened 2024-07-22 08:59 UTC by playX18

- Implemented `send_signal` and `system_reserve_gas`, `system_unreserve_gas`.
- Added helper methods to Gas tree manager to reserve/unreserve system gas.

@techraed

2024-07-23 18:01 UTC, techraed requested changes
Instead of creating another one wasm contract in `examples` I'd add system reservation functionality into `demo_constructor` and use it to create a desired logic instead another crate in the workspace.

2024-07-23 18:01 UTC, techraed commented on gtest/src/program.rs
> +        run_result.assert_panicked_with("Gotcha!");
Your test program actually sends a message `handle` from program to user, which must go to mailbox.
I'd adjust the test:
1. include some payload to the message (on the contract)
2. check here that there's a message in the mailbox with the same payload. 

Currently test doesn't actually check that signals work on gtest.

2024-07-26 11:14 UTC, techraed approved these changes

2024-07-26 11:14 UTC, techraed commented on gtest/src/program.rs
> +                Arg::bytes("Signal handled"),
please create a separate variable for the `Signal handled` string.

2024-07-26 11:14 UTC, techraed commented on gtest/src/program.rs
> +                Arg::bytes("Signal handled"),
as it is re-used

2024-07-30 19:07 UTC, techraed commented
@playX18 resolve conflict with master and merge it, please

2024-07-31 10:54 UTC, breathx requested changes

2024-07-31 10:54 UTC, breathx commented on Cargo.toml
> +sandbox-wasmi = { package = "wasmi", git = "https://github.com/gear-tech/wasmi", branch = "v0.13.2-sign-ext", features = [
I don't really like such formatting for features

2024-07-31 10:54 UTC, breathx commented on Cargo.toml
> +sandbox-wasmi = { package = "wasmi", git = "https://github.com/gear-tech/wasmi", branch = "v0.13.2-sign-ext", features = [
And everywhere else its stated differently

2024-07-31 10:54 UTC, breathx commented on gtest/src/manager.rs
> +            self.dispatches.push_front(trap_signal);
why front?

2024-07-31 10:54 UTC, breathx commented
Overall looks great. Push back into queue and resolve conflicts please

2024-08-01 18:42 UTC, breathx approved these changes
Still need to merge master

2024-08-02 06:37 UTC, merged