feat(common, gtest): add AuxiliaryTaskpool
gear-tech/gear pull request #4141
Opened 2024-08-12 04:34 UTC by playX18

Implementation of AuxiliaryTaskpool. At the moment not used in code. Once merged into master will work into merging it into [#4119](https://github.com/gear-tech/gear/pull/4119)

2024-08-12 10:31 UTC, breathx requested changes
discussed to implement deriving macro in separate pr first

2024-08-12 11:29 UTC, techraed reviewed
overall looks great
agree with @breathx, need to introduce macro

2024-08-13 15:35 UTC, techraed approved these changes

2024-08-14 10:08 UTC, breathx approved these changes

2024-08-14 10:09 UTC, merged