feat(ethexe): introduce test-only field status for Service
gear-tech/gear pull request #4182
Opened 2024-08-22 14:59 UTC by clearloop

Resolves #4099

share service status to caller environments, currently test-only features since this may not necessary for production

@gear-tech/dev

2024-08-22 15:07 UTC, breathx requested changes
Otherwise 👍🏻

2024-08-22 15:07 UTC, breathx commented on ethexe/cli/src/lib.rs
> +#![feature(stmt_expr_attributes)]
pls void nightly features

2024-08-25 23:48 UTC, clearloop commented on ethexe/cli/src/lib.rs
> +#![feature(stmt_expr_attributes)]
https://github.com/gear-tech/gear/pull/4182/commits/1b4e05a76ddb532a9a8e1c6c450fc2598fc94dc0

2024-09-04 18:12 UTC, breathx approved these changes

2024-09-05 08:43 UTC, merged