feat(ethexe/rpc): implement rpc methods
gear-tech/gear pull request #4299
Opened 2024-10-18 11:51 UTC by osipov-mit

2024-10-18 14:02 UTC, breathx requested changes

2024-10-18 14:02 UTC, breathx commented on ethexe/rpc/src/modules/program.rs
> +    async fn read_waitlist(&self, hash: H256) -> RpcResult<Waitlist>;
maybe add todo on expanding this? to query all the data by one query?

2024-10-18 14:02 UTC, breathx commented on ethexe/rpc/src/modules/program.rs
> +    async fn read_page_data(&self, hash: H256) -> RpcResult<PageBuf>;
you may want returning Bytes here due to vec/array base serialisation?

2024-10-18 14:02 UTC, breathx commented on ethexe/runtime/common/Cargo.toml
```suggestion
```

2024-10-18 14:02 UTC, breathx commented on ethexe/signer/src/lib.rs
> +                .to_hex_string(secp256k1::hashes::hex::Case::Lower)
use secp256k1::hashes::hex::Case;

```suggestion
                .to_hex_string(Case::Lower)
```

2024-10-18 14:02 UTC, breathx commented on ethexe/signer/src/lib.rs
> +            "Secret key: {:?}",
```suggestion
            "Secret key: {}",
```

2024-10-18 14:02 UTC, breathx commented on gprimitives/src/lib.rs
> +impl From<ActorId> for H160 {
better to impl method on ActorId or impl TryInto, since its only applicable in eth scenario, where first 12 bytes are meaningless and zeroed

2024-10-21 15:43 UTC, osipov-mit commented on ethexe/rpc/src/modules/program.rs
> +    #[method(name = "program_calculateReplyForHandle")]
As far as I got  jsonrpsee doesn't have that option

2024-10-21 15:46 UTC, osipov-mit commented on ethexe/common/src/lib.rs
> +use serde::Serialize;
I'm not sure if this is necessary cuz so far all these types are only used in the outputs of the rpc methods

2024-10-23 08:56 UTC, breathx commented on ethexe/common/src/lib.rs
> +use serde::Serialize;
Looks just like common practice, especially with almost-zero overhead

2024-10-23 08:56 UTC, breathx commented on ethexe/common/src/lib.rs
> +use serde::Serialize;
It will also help to impl some real-like conditions testing

2024-10-23 09:10 UTC, osipov-mit commented on ethexe/common/src/lib.rs
> +use serde::Serialize;
done

2024-11-04 09:06 UTC, breathx approved these changes

2024-11-05 09:03 UTC, merged