refactor(gmeta): gmeta crate removed completely
gear-tech/gear pull request #4347
Opened 2024-11-18 21:45 UTC by Lazark0x

gmeta crate removed, cleaned up other crates from gmeta

2025-02-13 13:12 UTC, breathx requested changes

2025-02-13 13:12 UTC, breathx commented on gcli/Cargo.toml
>  url = { workspace = true, features = ["serde"] }
wasmer dep seems unused now; if yes, remove it and all related

2025-02-13 13:12 UTC, breathx commented on pallets/gear/src/tests.rs
> -        assert_ok!(Gear::read_state_using_wasm_impl(
cfg test apis (Pallet impl) could be removed as well

2025-02-13 13:12 UTC, breathx commented on utils/wasm-builder/src/wasm_project.rs
> -extern "C" fn metahash() {{
are all metahash entries removed as well?

2025-02-13 13:12 UTC, breathx commented on utils/wasm-builder/src/wasm_project.rs
>          let mut wasm_paths: Option<(PathBuf, PathBuf)> = None;
no need in this tuple now?

2025-02-13 14:51 UTC, Lazark0x commented on utils/wasm-builder/src/wasm_project.rs
>          let mut wasm_paths: Option<(PathBuf, PathBuf)> = None;
why not? the function still returns tuple with paths to the original wasm and optimized ones

2025-02-14 08:47 UTC, Lazark0x commented on examples/fungible-token/src/lib.rs
> +pub use ft_io::*;
Maybe in the next pr I should redo the example so that I don't inflate the size of this pr?

2025-02-14 08:48 UTC, Lazark0x commented on gcli/Cargo.toml
>  url = { workspace = true, features = ["serde"] }
oops misclick.... thank you

2025-02-14 08:49 UTC, Lazark0x commented on Makefile
> -		-p gmeta -p gtest -p gear-wasm-builder -p gear-common \
oops misclick.... thank you

2025-02-14 08:51 UTC, Lazark0x commented on gcli/Cargo.toml
>  url = { workspace = true, features = ["serde"] }
you're right

2025-02-14 08:52 UTC, Lazark0x commented on pallets/gear/src/tests.rs
> -        assert_ok!(Gear::read_state_using_wasm_impl(
it looks like it's all been deleted

2025-02-14 08:53 UTC, Lazark0x commented on utils/wasm-builder/src/wasm_project.rs
> -extern "C" fn metahash() {{
yes, everything is removed except the api and runtime methods

2025-02-14 13:00 UTC, Lazark0x commented on examples/fungible-token/src/lib.rs
> +pub use ft_io::*;
moved types to lib.rs

2025-02-16 08:40 UTC, breathx approved these changes

2025-02-16 08:40 UTC, merged