feat(ethexe-tx-pool): Introduce basic tx-pool
gear-tech/gear pull request #4366
Opened 2024-11-28 12:52 UTC by techraed

This PR introduces a basic logic for the ethexe tx pool which works as following:
- Tx pool itself has a service part and a core part. The service part handles communications from outside to the core and from inside (core) to the outer "world". The core part basically performs main tx pool ops (adding a tx for now).
- The `InputTask` is a task that is requested to be executed by the tx pool. The task is sent via `TxPoolInputTaskSender` sending end of the channel between the sender and the tx pool service. The sendind end is supplied to the main service and the rpc. 
- Basic flow:
    1. Rpc receives a request for sending a tx. It sends the tx via the channel to the tx pool service.
    2. Tx pool service receives the `InputTask` and calls corresponding tx pool core method to handle the task.
    3. `InputTask::AddTransaction` task triggers tx pool core to 1) validate the transaction, 2) store it in db
    4. When the `InputTask::AddTransaction` is executed successfully the tx pool services sends `OutputTask::PropogateTransaction` to the main service. 
    5. The main service handles the `OutputTask::PropogateTransaction` by gossiping it to other nodes.
    6. When a node receives a transaction, it creates `InputTask::AddTransaction` task and sends it to the tx pool. If tx exists, it's not added to the storage.

Here you can also find a tiny refactoring of the `ethexe-signer` which is all about clarifying comments, simplified API and moving types to their own modules.

2025-01-08 13:56 UTC, StackOverflowExcept1on commented on ethexe/signer/src/lib.rs
> +//! Cryptographic instrumentary of the crate is based on secp256k1 standard
mb it makes sense to replace crate secp256k1 with k256:
- alloy also uses k256 (less dependencies to build)
- it's pure rust implementation (secp256k1 uses secp256k1-sys)

2025-01-15 18:10 UTC, techraed commented on ethexe/signer/src/lib.rs
> +//! Cryptographic instrumentary of the crate is based on secp256k1 standard
That's a great note.
Transitioning to the k256 is out of the PR context, but can be done in the other PR.

2025-01-16 09:52 UTC, StackOverflowExcept1on commented on ethexe/signer/src/lib.rs
> +//! Cryptographic instrumentary of the crate is based on secp256k1 standard
tracking issue - #4443

2025-01-16 11:04 UTC, techraed commented on ethexe/signer/src/lib.rs
> +//! Cryptographic instrumentary of the crate is based on secp256k1 standard
resolved in favor of #4443

2025-01-17 07:47 UTC, techraed reviewed
after review call

2025-01-17 07:47 UTC, techraed commented on ethexe/tx-pool/src/validation.rs
> +        let Some(task_sender) = self.executable_tx_check.as_ref() else {
review: instead of sending task to the main service, instantiate `Processor` and do the job here

2025-01-17 07:47 UTC, techraed commented on ethexe/tx-pool/src/service.rs
> +                InputTask::ValidateTransaction {
```suggestion
                InputTask::ValidatePreDispatch {
```

2025-01-17 07:47 UTC, techraed commented on ethexe/tx-pool/src/transaction.rs
> +pub trait TransactionTrait:
remove traits

2025-01-17 08:09 UTC, techraed commented on ethexe/tx-pool/src/transaction.rs
> +pub trait TransactionTrait:
done

2025-01-17 08:09 UTC, techraed commented on ethexe/tx-pool/src/service.rs
> +                InputTask::ValidateTransaction {
done

2025-01-20 10:04 UTC, techraed commented on ethexe/tx-pool/src/validation.rs
> +        let Some(task_sender) = self.executable_tx_check.as_ref() else {
done

2025-02-06 17:47 UTC, techraed commented on ethexe/tx-pool/src/lib.rs
> +impl Stream for TxPoolService {
@breathx I'm not sure that we really need it in the current design, as after TxPoolService::process returnes successfully `Ok` in the main service `tokio::select` statement, we can just call propagation procedures without any need in this intermediate stream

2025-02-10 09:34 UTC, breathx requested changes

2025-02-10 09:34 UTC, breathx commented on ethexe/network/src/lib.rs
> +    pub fn publish_transaction(&mut self, data: Vec<u8>) {
offchain_transaction. I'd go with this naming everywhere in case for future features append etc

2025-02-10 09:34 UTC, breathx commented on ethexe/common/src/tx_pool.rs
> +    /// Reference block hash is used for a transcation mortality check.
typos check pls 
```suggestion
    /// Reference block hash is used for a transaсtion mortality check.
```

2025-02-10 09:34 UTC, breathx commented on ethexe/network/src/lib.rs
>      gossipsub::IdentTopic::new("gpu-commitments")
```suggestion
    gossipsub::IdentTopic::new("ethexe-commitments")
```

2025-02-10 09:34 UTC, breathx commented on ethexe/network/src/lib.rs
> +    gossipsub::IdentTopic::new("tx")
```suggestion
    gossipsub::IdentTopic::new("ethexe-tx-pool")
```

2025-02-10 09:34 UTC, breathx commented on ethexe/rpc/src/apis/tx_pool.rs
> +// Copyright (C) 2024 Gear Technologies Inc.
'25

2025-02-10 09:34 UTC, breathx commented on ethexe/rpc/src/apis/tx_pool.rs
> +        program_id: H160,
I'd consider using here "common::" type just for more friendly target code (js), so nobody's forget across which type we create signature etc

2025-02-10 09:34 UTC, breathx commented on ethexe/rpc/src/apis/tx_pool.rs
> +        program_id: H160,
moreover, please append todo or impl within the pr cli to submit offchain txs (more likely todo)

2025-02-10 09:34 UTC, breathx commented on ethexe/rpc/src/apis/tx_pool.rs
> +                errors::internal()
it's better to extend ux of error in rpc bypassing error description

2025-02-10 09:34 UTC, breathx commented on ethexe/rpc/src/apis/tx_pool.rs
> +                errors::internal()
like why and how

2025-02-10 09:34 UTC, breathx commented on ethexe/service/src/lib.rs
> +                                    if let Ok(validated_tx) = tx_pool.process(transaction) {
else warn or debug

2025-02-10 09:34 UTC, breathx commented on ethexe/service/src/lib.rs
> +                    match event {
there should be network propagation

2025-02-10 09:34 UTC, breathx commented on ethexe/service/src/lib.rs
> +                            let res = tx_pool.process(transaction).map(|validated_tx| {
what process exactly does?

2025-02-10 09:34 UTC, breathx commented on ethexe/signer/Cargo.toml
> +alloy = { workspace = true, features = ["k256"] }
why implementing it within the pr instead of opening another one?

2025-02-10 09:34 UTC, breathx commented on ethexe/signer/src/address.rs
> +impl TryFrom<ActorId> for Address {
from u64 using ActorIds impl would be useful

2025-02-10 09:34 UTC, breathx commented on ethexe/signer/src/utils.rs
> +pub(crate) fn strip_prefix(s: &str) -> &str {
`s.strip_prefix("0x").unwrap_or(s)` is pretty easy to use so overall this utils mod seems useless. decode_to_array could be declared in place of use

2025-02-10 09:34 UTC, breathx commented on ethexe/tx-pool/Cargo.toml
> +anyhow.workspace = true
reorganise to highlight external and internal deps as its done everywhere else in ethexe

2025-02-10 09:34 UTC, breathx commented on ethexe/tx-pool/src/lib.rs
> +use anyhow::{Context as _, Result};
mv to top

2025-02-10 09:34 UTC, breathx commented on ethexe/tx-pool/src/lib.rs
> +    ready_tx: VecDeque<SignedTransaction>,
I'd keep here a map hash -> tx

2025-02-10 09:34 UTC, breathx commented on ethexe/tx-pool/src/lib.rs
> +                self.readiness_sender
what's this readiness?

2025-02-10 09:34 UTC, breathx commented on ethexe/tx-pool/src/lib.rs
> +impl Stream for TxPoolService {
at this moment it seems that we don't need any event here at all, yeah

2025-02-10 09:34 UTC, breathx commented on ethexe/tx-pool/src/lib.rs
> +        ready!(self.readiness_receiver.poll_recv(cx)).expect("sender is always alive");
that's a hack)) should be done by pending_events vecdeque and waker call

2025-02-10 09:34 UTC, breathx commented on ethexe/tx-pool/src/lib.rs
> +pub fn tx_send_message_source(tx: &SignedTransaction) -> Result<H160> {
-> Res<ActorId>

2025-02-10 09:34 UTC, breathx commented on ethexe/tx-pool/src/lib.rs
> +fn tx_signature(tx: &SignedTransaction) -> Result<Signature> {
append this logic to tx type itself?

2025-02-10 09:34 UTC, breathx commented on ethexe/tx-pool/src/validation.rs
> +    fn check_uniqueness(&self) -> Result<()> {
uniqueness check will require check of recent blocks inner data. please fix or open an issue.
why: we can't just mark something as done/performed since reorg can happen

2025-02-10 09:34 UTC, breathx commented on ethexe/tx-pool/src/validation.rs
> +        assert!(TxValidator::new(transaction, db.clone())
assert err

2025-02-10 09:34 UTC, breathx commented on ethexe/tx-pool/src/validation.rs
> +        assert!(TxValidator::new(transaction, db.clone())
everywhere

2025-02-10 11:24 UTC, techraed commented on ethexe/db/src/database.rs
> +        let Some(reference_block_header) = self.block_header(reference_block_hash) else {
the `Result` is returned on the upper level during tx validation. Each `false` case is an `Err` case.

2025-02-10 12:02 UTC, techraed commented on ethexe/rpc/src/apis/tx_pool.rs
> +                errors::internal()
The RPC is available is an external interface. Do we really need to give details to the external client of what happened inside? Also, these errors are about the fact that something internally has crashed. By something, I mean the main service thread has crashed, or logic is malformed. That will be logged on the node, but shouldn't be returned to the client.

Unless RPC is exposed not to the "all world"..?

2025-02-10 12:09 UTC, techraed commented on ethexe/service/src/lib.rs
> +                            let res = tx_pool.process(transaction).map(|validated_tx| {
renamed to `validate` as previously it wasn't only about validation, but also the method pushed the event

2025-02-10 12:10 UTC, techraed commented on ethexe/signer/Cargo.toml
> +alloy = { workspace = true, features = ["k256"] }
That was a part of signed related refactoring and historically was considered to be something easy and fast to merge. Now we are here.

2025-02-10 12:30 UTC, techraed commented on ethexe/tx-pool/src/lib.rs
> +fn tx_signature(tx: &SignedTransaction) -> Result<Signature> {
can't be done, as then `ethexe-common` must depend on `ethexe-signed`, but `ethexe-signer` already depends on `ethexe-common`. Must be reorganised completely. It's a subject of further discussions

2025-02-10 14:02 UTC, techraed commented on ethexe/common/src/tx_pool.rs
> +        gear_core::ids::hash(&self.encode()).into()
done

2025-02-10 14:02 UTC, techraed commented on ethexe/common/src/tx_pool.rs
> +    pub fn reference_block_hash(&self) -> H256 {
done

2025-02-10 14:02 UTC, techraed commented on ethexe/common/src/tx_pool.rs
> +        value: u128,
done

2025-02-10 14:02 UTC, techraed commented on ethexe/common/src/tx_pool.rs
> +pub struct Transaction {
done

2025-02-10 14:02 UTC, techraed commented on ethexe/db/src/database.rs
> +const BLOCK_HASHES_WINDOW_SIZE: u32 = 30;
done

2025-02-10 14:02 UTC, techraed commented on ethexe/db/src/database.rs
> +    pub fn validated_transaction(&self, tx_hash: H256) -> Option<SignedTransaction> {
done

2025-02-10 14:03 UTC, techraed commented on ethexe/db/src/database.rs
> +        let Some(reference_block_header) = self.block_header(reference_block_hash) else {
done

2025-02-10 14:03 UTC, techraed commented on ethexe/db/src/database.rs
> +        if latest_valid_block_header.height - reference_block_header.height
done

2025-02-10 14:03 UTC, techraed commented on ethexe/db/src/database.rs
> +            let Some(block_header) = self.block_header(block_hash) else {
done

2025-02-10 14:03 UTC, techraed commented on ethexe/network/src/lib.rs
> +    pub fn publish_transaction(&mut self, data: Vec<u8>) {
done

2025-02-10 14:03 UTC, techraed commented on ethexe/common/src/tx_pool.rs
> +    /// Reference block hash is used for a transcation mortality check.
done

2025-02-10 14:03 UTC, techraed commented on ethexe/network/src/lib.rs
>      gossipsub::IdentTopic::new("gpu-commitments")
done

2025-02-10 14:07 UTC, techraed commented on ethexe/network/src/lib.rs
> +    gossipsub::IdentTopic::new("tx")
done

2025-02-10 14:07 UTC, techraed commented on ethexe/rpc/src/apis/tx_pool.rs
> +// Copyright (C) 2024 Gear Technologies Inc.
done

2025-02-10 14:09 UTC, techraed commented on ethexe/rpc/src/apis/tx_pool.rs
> +        program_id: H160,
done

2025-02-10 14:09 UTC, techraed commented on ethexe/service/src/lib.rs
> +                                    if let Ok(validated_tx) = tx_pool.process(transaction) {
done

2025-02-10 14:09 UTC, techraed commented on ethexe/service/src/lib.rs
> +                    match event {
done

2025-02-10 14:10 UTC, techraed commented on ethexe/signer/src/address.rs
> +impl TryFrom<ActorId> for Address {
done

2025-02-10 14:10 UTC, techraed commented on ethexe/tx-pool/Cargo.toml
> +anyhow.workspace = true
done

2025-02-10 14:10 UTC, techraed commented on ethexe/tx-pool/src/lib.rs
> +use anyhow::{Context as _, Result};
done

2025-02-10 14:11 UTC, techraed commented on ethexe/tx-pool/src/lib.rs
> +    ready_tx: VecDeque<SignedTransaction>,
not actual, stream removed

2025-02-10 14:11 UTC, techraed commented on ethexe/tx-pool/src/lib.rs
> +                self.readiness_sender
not actual, stream removed

2025-02-10 14:11 UTC, techraed commented on ethexe/tx-pool/src/lib.rs
> +        ready!(self.readiness_receiver.poll_recv(cx)).expect("sender is always alive");
discussed
not actual, stream removed

2025-02-10 14:11 UTC, techraed commented on ethexe/tx-pool/src/lib.rs
> +pub fn tx_send_message_source(tx: &SignedTransaction) -> Result<H160> {
done

2025-02-10 14:11 UTC, techraed commented on ethexe/tx-pool/src/validation.rs
> +        assert!(TxValidator::new(transaction, db.clone())
done

2025-02-16 09:56 UTC, breathx approved these changes

2025-02-16 09:56 UTC, breathx commented on core/src/lib.rs
> +pub use ids::{hash, hash_of_array};
imo this better to be moved somewhere like utils mod/root rather than just reexported

2025-02-16 09:56 UTC, breathx commented on ethexe/common/src/tx_pool.rs
> +    pub signature: Vec<u8>,
what if we use here Signature type from ethexe_signer?

2025-02-16 09:56 UTC, breathx commented on ethexe/db/src/database.rs
> +    pub fn check_within_recent_blocks(&self, reference_block_hash: H256) -> Result<()> {
I'd still separate here cases of Err and "false" by returning Result<bool> giving much more space and flexibility in the end code using this api

2025-02-16 09:56 UTC, breathx commented on ethexe/db/src/database.rs
> +            .get(&KeyPrefix::Transaction.one(tx_hash))
maybe specify in keyPrefix that it's "Signed" type to avoid misuse?

2025-02-16 09:56 UTC, breathx commented on ethexe/rpc/src/apis/tx_pool.rs
> +                errors::internal()
We can come back to this topic later. In my opinion, not all of the errors happening here are internal. For example, an attempt to send offchain tx messaging inexistent program

2025-02-16 09:56 UTC, breathx commented on ethexe/rpc/src/lib.rs
> +        response_sender: oneshot::Sender<Result<H256>>,
I'd put here Option with custom Clone impl in favor of ease of use for @playX18 in his PR of  global events broadcasting

2025-02-16 09:56 UTC, breathx commented on ethexe/service/src/lib.rs
> +        tx_pool: TxPoolService,
pretty much interesting question should tx pool be an optional service: basically, it depends both on network and rpc which are optional, but when they're enabled, it must be enabled as well

2025-02-16 09:56 UTC, breathx commented on ethexe/service/src/tests.rs
> +        pub service_rpc_config: Option<RpcConfig>,
analogue with network field 2 lines above 
```suggestion
        pub rpc: Option<RpcConfig>,
```

2025-02-16 09:56 UTC, breathx commented on ethexe/service/src/tests.rs
> +    // Send request
some rpc wrapper for sending requests would be much more user-friendly

2025-02-16 09:56 UTC, breathx commented on ethexe/signer/src/lib.rs
> +            None => bail!("Address not found: {}", address),
```suggestion
            None => anyhow!("Address not found: {address}"),
```

2025-02-16 09:56 UTC, breathx commented on ethexe/tx-pool/src/tests.rs
> +    let public_key = signer
you can just create here keypair

2025-02-16 09:56 UTC, breathx commented on ethexe/tx-pool/src/tests.rs
> +        timestamp: 0,
I'd avoid potential invalidations of test env caused by incorrect height and timestamp

2025-02-16 09:56 UTC, breathx commented on ethexe/tx-pool/src/validation.rs
> +    fn check_mortality(&self) -> Result<()> {
for each check pls follow the same as for check_within_n_blocks: Result<bool>, err bailing only in case of storage invariants braking

2025-02-16 11:04 UTC, techraed commented on ethexe/common/src/tx_pool.rs
> +    pub signature: Vec<u8>,
Well, there's an invariant inside `Signature` and `RawSignature`, but it's not applied on a type level. So technically there are no issues with that, but from semantics perspective it looks wrong. Especially while having this: https://github.com/gear-tech/gear/blob/e482b4a27432b7f0a406783a4a34c199a3b71e85/ethexe/signer/src/signature.rs#L76

2025-02-16 11:10 UTC, techraed commented on ethexe/rpc/src/apis/tx_pool.rs
> +                errors::internal()
I agree with that. 
Сurrently the underlying impl is not ready for the separation of internal and external errors (everything is hidden under anyhow).

2025-02-16 12:43 UTC, techraed commented on ethexe/signer/src/lib.rs
> +            None => bail!("Address not found: {}", address),
it should return `Err(anyhow!(...))`, which is the same as `bail!`

2025-02-16 13:21 UTC, techraed commented on ethexe/service/src/lib.rs
> +        tx_pool: TxPoolService,
as discussed added TODO for the network

2025-02-16 13:32 UTC, techraed commented on core/src/lib.rs
> +pub use ids::{hash, hash_of_array};
done

2025-02-16 13:32 UTC, techraed commented on ethexe/db/src/database.rs
> +    pub fn check_within_recent_blocks(&self, reference_block_hash: H256) -> Result<()> {
done

2025-02-16 13:32 UTC, techraed commented on ethexe/db/src/database.rs
> +            .get(&KeyPrefix::Transaction.one(tx_hash))
done

2025-02-16 13:32 UTC, techraed commented on ethexe/rpc/src/lib.rs
> +        response_sender: oneshot::Sender<Result<H256>>,
done

2025-02-16 13:32 UTC, techraed commented on ethexe/service/src/tests.rs
> +        pub service_rpc_config: Option<RpcConfig>,
done

2025-02-16 13:32 UTC, techraed commented on ethexe/service/src/tests.rs
> +    // Send request
done

2025-02-16 13:33 UTC, techraed commented on ethexe/tx-pool/src/tests.rs
> +    let public_key = signer
done

2025-02-16 13:33 UTC, techraed commented on ethexe/tx-pool/src/tests.rs
> +        timestamp: 0,
done

2025-02-16 13:34 UTC, techraed commented on ethexe/tx-pool/src/validation.rs
> +    fn check_mortality(&self) -> Result<()> {
done

2025-02-17 12:52 UTC, breathx commented on ethexe/common/src/tx_pool.rs
> +    pub signature: Vec<u8>,
discussed to be done in separate PR

2025-02-17 12:58 UTC, breathx approved these changes

2025-02-17 12:58 UTC, breathx commented on ethexe/rpc/src/lib.rs
> +pub mod test_utils;
cfg feature test utils?

2025-02-17 14:23 UTC, techraed commented on ethexe/rpc/src/lib.rs
> +pub mod test_utils;
sure

2025-02-17 15:28 UTC, techraed commented on ethexe/service/src/tests.rs
> +    let rpc_client = RpcClient::new(node0.service_rpc_url().expect("rpc server is set"));
done

2025-02-17 20:05 UTC, merged