feat(code-backend) implemented extractors in backend to avoid accidental memory registry creation
gear-tech/gear pull request #4381
Opened 2024-12-07 23:22 UTC by Lazark0x

Resolves #3891 

Implemented extractors as proposed in issue #3891 
Extractors are used in methods with a variable number of arguments, while having a variable number of constructor arguments themselves.
After all extractors have been created, the MemoryAccessRegistry::pre_process() method is called
If the method did not need any extractors, the MemoryAccessRegistry::pre_process() method will not be called either

2025-01-13 15:04 UTC, breathx requested changes

2025-01-13 15:04 UTC, breathx commented on core-backend/src/funcs.rs
> +    pub fn read(at: u32, buffer: Write) -> impl Syscall<Caller> {
isn't it a bug, changing order of args?

2025-01-13 16:50 UTC, Lazark0x commented on core-backend/src/funcs.rs
> +    pub fn read(at: u32, buffer: Write) -> impl Syscall<Caller> {
Yeah, but no. The arguments are in reverse order, but there is no other way but to change the syscall signature, which is obviously not worth it.

```
let ptr = SyscallValue(args[1]).try_into()?;
let size = SyscallValue(args[0]).try_into()?;
```

2025-04-07 18:17 UTC, ark0f requested changes

2025-04-07 18:17 UTC, ark0f commented on core-backend/src/funcs.rs
> +    fn gas(&self) -> Option<Gas> {
I actually do not see the reason of such changes (for `run_fallible` and `run_any`, too). Could you clarify, please?

2025-04-07 18:17 UTC, ark0f commented on core-backend/src/accessors.rs
> +    pub fn value(self) -> Result<Vec<u8>, MemoryAccessError> {
```suggestion
    pub fn into_inner(self) -> Result<Vec<u8>, MemoryAccessError> {
```

2025-04-07 18:17 UTC, ark0f commented on core-backend/src/runtime.rs
> +            None => Err(MemoryAccessError::ManagerError),
```suggestion
            None => unreachable!(),
```
Syscall didn't set its requirement for the manager and thus implementation is invalid and should be never met in runtime

2025-04-07 18:17 UTC, ark0f commented on core-backend/src/funcs.rs
> +                    let io = registry.unwrap().pre_process(caller);
Error can be set like in `CallerWrap::set_termination_reason()` and `HostError` returned, so you don't need to handle late return

2025-04-18 18:51 UTC, Lazark0x commented on core-backend/src/funcs.rs
> +                }
Done

2025-04-18 18:52 UTC, Lazark0x commented on core-backend/src/funcs.rs
> +                }
I agree, thanks

2025-04-18 18:52 UTC, Lazark0x commented on core-backend/src/funcs.rs
> +        }
Done

2025-04-18 18:53 UTC, Lazark0x commented on core/src/memory.rs
> +    fn write(&self, ctx: &Context, offset: u32, buffer: &[u8]) -> Result<(), MemoryError>;
Okay, that's possible

2025-04-18 18:54 UTC, Lazark0x commented on core-backend/src/accessors.rs
> +        }
Done

2025-04-18 18:54 UTC, Lazark0x commented on core-backend/src/accessors.rs
> +            Ok(Some(registry.as_mut().unwrap().register_read(ptr, size)))
Yeah, you're right, thanks

2025-04-18 18:56 UTC, Lazark0x commented on core-backend/src/accessors.rs
> +    type Output = Option<WasmMemoryRead>;
I rewrote it with your version

2025-04-18 19:08 UTC, Lazark0x commented on core-backend/src/funcs.rs
> +    fn gas(&self) -> Option<Gas> {
Getting gas from SyscallContext is necessary to set the amount of gas in Ext::decrease_current_counter_to() before calling Builder::build() and Syscall::execute(), because MemoryAccessRegistry::pre_process() consumes gas that we would not otherwise include

2025-04-18 19:09 UTC, Lazark0x commented on core-backend/src/runtime.rs
> +            None => Err(MemoryAccessError::ManagerError),
Agree

2025-04-18 19:15 UTC, Lazark0x commented on core-backend/src/funcs.rs
> +                    let io = registry.unwrap().pre_process(caller);
This would be a great idea, we could get rid of a lot of code, except for the fact that when an error occurs in FallibleSyscall, the error content is written to memory in different formats depending on the type of syscall

2025-04-28 21:02 UTC, ark0f requested changes

2025-05-12 17:53 UTC, Lazark0x commented on core-backend/src/funcs.rs
> +                let ARGS_AMOUNT: usize = 0 $( + $generic::REQUIRED_ARGS )+;
I can't do this because of the fact that these generics are declared at the impl level, not at the function level [E0401](https://doc.rust-lang.org/error_codes/E0401.html)
And rust's compiler «hoist» for inner consts

2025-05-12 17:54 UTC, Lazark0x commented on core-backend/src/accessors.rs
> +    result: Result<Result<Vec<u8>, MemoryAccessError>, PayloadSizeError>,
Done

2025-05-12 17:55 UTC, Lazark0x commented on core-backend/src/funcs.rs
> +                debug_assert_eq!(args.len(), ARGS_AMOUNT);
Thanks, my mistake

2025-05-12 17:57 UTC, Lazark0x commented on core-backend/src/funcs.rs
> +    fn gas(&self) -> Option<Gas> {
All in all I don't know what would be the best way to do it, let it be your variant =)

2025-05-15 10:55 UTC, breathx approved these changes
Lgtm

@ark0f pls take another look

2025-05-15 10:55 UTC, breathx commented on core-backend/src/runtime.rs
> +    pub memory_wrap: MemoryAccessIoWrap<Caller>,
> This is done specifically to be able to get mut refs to both of these structure fields for cases like: `io.write(&mut ctx.caller_wrap, ...)` where `io` is `&mut MemoryAccessIo`

for cases like gr_read?

2025-05-15 10:55 UTC, breathx commented on core-backend/src/accessors.rs
> +                result: Ok(Default::default()),
should we return option for the case?

2025-05-15 10:55 UTC, breathx commented on core-backend/src/funcs.rs
> +    fn from_args(args: &[Value]) -> Result<(Self, Option<Gas>, &[Value]), HostError>;
why is gas optional?

2025-05-15 10:55 UTC, breathx commented on core-backend/src/funcs.rs
> +        let FallibleSyscallContext { res_ptr, .. } = context;
remove this trampoline for future errors from everywhere please
```suggestion
        let FallibleSyscallContext { res_ptr } = context;
```

2025-05-15 10:55 UTC, breathx commented on core-backend/src/funcs.rs
> +        payload: ReadPayloadLimited,
can we maybe do it somehow like ReadAs< PayloadLimited >?

2025-05-15 10:55 UTC, breathx commented on core-backend/src/funcs.rs
> +    pub fn size(size_write: WriteAs<[u8; 4]>) -> impl Syscall<Caller> {
WriteAS< u32 > doesnt work? u32: Encode resulting in le bytes

2025-05-15 10:55 UTC, breathx commented on core-backend/src/funcs.rs
> +    pub fn message_id(message_id_write: WriteAs<[u8; 32]>) -> impl Syscall<Caller> {
etc 
```suggestion
    pub fn message_id(message_id_write: WriteAs<MessageId>) -> impl Syscall<Caller> {
```

2025-05-16 09:00 UTC, Lazark0x commented on core-backend/src/runtime.rs
> +    pub memory_wrap: MemoryAccessIoWrap<Caller>,
Yep, and for any write call, where we need `&mut ctx`

2025-05-16 09:17 UTC, Lazark0x commented on core-backend/src/funcs.rs
> +        payload: ReadPayloadLimited,
Certainly not as `ReadAs`, because reading a payload requires a length argument as well, `ReadAs` only works for structures with known size
The need for `ReadPayloadLimited` comes from the encapsulation of early length checking and the conversion of bytes into `Payload`

2025-05-16 10:20 UTC, Lazark0x commented on core-backend/src/funcs.rs
> +    pub fn size(size_write: WriteAs<[u8; 4]>) -> impl Syscall<Caller> {
Yeah, you're right, converting to bytes was redundant here

2025-05-16 10:20 UTC, Lazark0x commented on core-backend/src/funcs.rs
> +    pub fn message_id(message_id_write: WriteAs<[u8; 32]>) -> impl Syscall<Caller> {
Yep

2025-05-16 10:22 UTC, Lazark0x commented on core-backend/src/funcs.rs
> +        let FallibleSyscallContext { res_ptr, .. } = context;
Ok

2025-05-16 10:25 UTC, Lazark0x commented on core-backend/src/funcs.rs
> +    fn from_args(args: &[Value]) -> Result<(Self, Option<Gas>, &[Value]), HostError>;
Since we have an `impl SyscallContext for ()` that doesn't have gas

2025-05-16 10:35 UTC, Lazark0x commented on core-backend/src/accessors.rs
> +                result: Ok(Default::default()),
The original code from `fn register_and_read_value` returned 0 if the address matched `PTR_SPECIAL`, I think this is the desired behavior...

2025-05-19 07:44 UTC, breathx commented on core-backend/src/funcs.rs
> +    fn from_args(args: &[Value]) -> Result<(Self, Option<Gas>, &[Value]), HostError>;
seems we could remove it? @ark0f ?

2025-05-19 07:45 UTC, breathx commented on core-backend/src/accessors.rs
> +                result: Ok(Default::default()),
just from coding perspective 
meet PTR_SPECIAL => return None => unwrap_or_default 
but not a big deal actually

2025-05-19 07:48 UTC, breathx approved these changes
once replied by @ark0f, maybe better to remove option for gas - otherwise looks good

2025-05-27 15:10 UTC, ark0f approved these changes
🎉

2025-05-27 15:10 UTC, ark0f commented on core-backend/src/funcs.rs
> +                }
```suggestion
                debug_assert_eq!(index, ARGS_AMOUNT);
```

2025-06-17 09:42 UTC, Lazark0x commented on core-backend/src/funcs.rs
> +    fn from_args(args: &[Value]) -> Result<(Self, Option<Gas>, &[Value]), HostError>;
`RawSyscall` replaced with `InfallibleSyscall` with `Null` gas cost

2025-06-18 13:12 UTC, merged