feat(wasm-builder): switch to new `wasm32v1-none` target
gear-tech/gear pull request #4407
Opened 2024-12-18 10:54 UTC by StackOverflowExcept1on

Resolves #4235 by switching to new `wasm32v1-none` target.
- requires Rust 1.84 (will be stable on January 9, 2025).
- `-C target-feature=+sign-ext` also works for `core` and `alloc` without `-Zbuild-std`.
- `-C linker-plugin-lto` still doesn't work and we can't remove panic locations.

Output WASM files are now in different location:
```diff
- ./target/<target>/<profile>/demo_vec.wasm
+ ./target/<profile>/wasms/demo_vec.wasm
```

2025-01-09 17:20 UTC, StackOverflowExcept1on commented on .github/workflows/PR.yml
> +    #branches: [master]
should be removed

2025-01-09 17:20 UTC, StackOverflowExcept1on commented on utils/cargo-gbuild/src/cli.rs
> +        // TODO: not sure how to set target dir here
should be removed

2025-01-09 18:32 UTC, StackOverflowExcept1on commented on Cargo.toml
> +substrate-wasm-builder = { version = "24.0.1", git = "https://github.com/gear-tech/polkadot-sdk.git", branch = "gear-polkadot-stable2409-wasm32v1-none" }
now `substrate-wasm-builder` is used from the `gear-polkadot-stable2409-wasm32v1-none` branch: 
https://github.com/gear-tech/polkadot-sdk/commit/761ea7010f91f195c3d3b9d8b22c75f59ff23dce

2025-01-11 21:51 UTC, StackOverflowExcept1on commented on utils/wasm-optimizer/src/cargo_toolchain.rs
> +        rustup toolchain install {x} --component llvm-tools --target wasm32v1-none\n\n\
there is no point in advising to install the llvm-tools component, which is only used for runtime fuzzer to ecosystem developer

2025-01-13 16:13 UTC, ark0f requested changes

2025-01-13 16:13 UTC, ark0f commented on .github/workflows/build.yml
> +          tar czvf artifact/examples.tar.gz target/release/wasms/*.wasm
It would be nice to have path like this to be consistent how `cargo` creates folders for specified target (e.g. `gear-wasm` can be imagined as virtual target)

```suggestion
          tar czvf artifact/examples.tar.gz target/gear-wasm/release/*.wasm
```

2025-01-13 16:16 UTC, ark0f commented on Cargo.toml
> +substrate-wasm-builder = { version = "24.0.1", git = "https://github.com/gear-tech/polkadot-sdk.git", branch = "gear-polkadot-stable2409-wasm32v1-none" }
Could you explain the point to patch Substrate to use new target? I think it's up to Substrate what it uses

2025-01-13 19:28 UTC, StackOverflowExcept1on commented on Cargo.toml
> +substrate-wasm-builder = { version = "24.0.1", git = "https://github.com/gear-tech/polkadot-sdk.git", branch = "gear-polkadot-stable2409-wasm32v1-none" }
To remove the `rust-src` component and `wasm32-unknown-unknown` target from `rust-toolchain.toml` (less binaries need to be downloaded). Also see paritytech/polkadot-sdk#7008 where I have already received 2 approves for this change.

2025-01-14 09:59 UTC, StackOverflowExcept1on commented on .github/workflows/build.yml
> +          tar czvf artifact/examples.tar.gz target/release/wasms/*.wasm
Good idea, but I don't like naming. Maybe `wasm32-gear` would be more suitable?

2025-01-17 05:01 UTC, breathx requested changes

2025-01-17 05:01 UTC, breathx commented on utils/wasm-builder/src/wasm_project.rs
> +        wasm_target_dir.push("gear-wasm");
```suggestion
        wasm_target_dir.push("wasm32-gear");
```

2025-01-17 05:02 UTC, breathx commented on utils/wasm-builder/src/wasm_project.rs
> +        wasm_target_dir.push("gear-wasm");
how did you pass CI? 🤔

2025-01-17 05:23 UTC, StackOverflowExcept1on commented on utils/wasm-builder/src/wasm_project.rs
> +        wasm_target_dir.push("gear-wasm");
ok, let's run wasm builder smoke tests on CI: https://github.com/gear-tech/gear/actions/runs/12823207597

2025-02-03 14:55 UTC, breathx approved these changes

2025-02-03 19:19 UTC, ark0f approved these changes
Don't forget to merge updates from `gear-polkadot-stable2409` or merge your changes into that branch

2025-02-04 06:12 UTC, merged