refactor(backend): refine approach of funcs forbidding
gear-tech/gear pull request #4409
Opened 2024-12-19 09:37 UTC by Lazark0x

Resolves #4399 .

Moved syscalls forbiddenes check to backend side

2025-01-11 20:06 UTC, breathx requested changes
Except the comment, looks good 👍🏻

2025-01-11 20:06 UTC, breathx commented on core/src/env.rs
> +    /// Return the set of functions that are forbidden to be called in this endpoint.
I'd remove this. On backend side for each execution better to accept some "forbidden_funcs". Endpoint one's to be taken on backend from kind itself

2025-01-14 11:52 UTC, Lazark0x commented on core-backend/src/funcs.rs
> +        _syscall_name: SyscallName,
Yes, added processing to RawSyscall as well

2025-01-14 14:32 UTC, breathx commented on core-backend/src/runtime.rs
> +        let endpoint_forbidden_funcs = self.ext_mut().endpoint_dispatch_kind().forbidden_funcs();
maybe inverse this check into ?
entry.forbids(call) -> bool

2025-01-14 14:32 UTC, breathx commented on core-processor/src/executor.rs
> +        endpoint_dispatch_kind: kind,
better to do as a part of message ctx

2025-01-14 22:24 UTC, Lazark0x commented on core-backend/src/runtime.rs
> +        let endpoint_forbidden_funcs = self.ext_mut().endpoint_dispatch_kind().forbidden_funcs();
Yeah, that seems like a more direct solution

2025-01-14 22:24 UTC, Lazark0x commented on core-processor/src/executor.rs
> +        endpoint_dispatch_kind: kind,
I'd agree

2025-01-17 05:10 UTC, breathx approved these changes

2025-01-17 05:10 UTC, breathx commented on core-backend/src/runtime.rs
> +                .endpoint_dispatch_kind()
doesn't it make more sense from where we take this value?
```suggestion
                .ext_mut()
                .msg_ctx()
                .dispatch_kind()
                .forbids(x)
```

2025-01-17 05:10 UTC, breathx commented on core-backend/src/runtime.rs
> +                .endpoint_dispatch_kind()
it's not like it belongs to endpoint

2025-02-11 10:13 UTC, Lazark0x commented on core-backend/src/runtime.rs
> +                .endpoint_dispatch_kind()
Agree

2025-02-13 13:47 UTC, breathx approved these changes

2025-02-13 13:49 UTC, merged