Node runtime tests
gear-tech/gear pull request #651
Opened 2022-02-11 00:16 UTC by ukint-vs

Resolves #581 .

-
-
-

@gear-tech/dev

2022-02-11 18:35 UTC, ekovalev approved these changes

2022-02-15 08:31 UTC, NikVolf commented on utils/gear-runtime-test-cli/src/mock.rs
> +construct_runtime!(
Nope, we need to test it on real runtime from `node-runtime`

2022-02-15 08:32 UTC, NikVolf requested changes
Need to test it on real runtime like rpc tests we replace do

2022-02-16 15:11 UTC, NikVolf approved these changes

2022-02-16 15:13 UTC, merged