Implement Ext in crates
gear-tech/gear pull request #927
Opened 2022-05-11 19:15 UTC by ukint-vs

Resolves #921.

- Implement default `Ext` members.
- Remove `LazyPagesExt`.
- Add `Ext` into `gear-test` and `gtest`.

Todo:
- [ ] Reduce code duplicate.
- [ ] Try to avoid interactions directly with `Ext` struct fields.

@gear-tech/dev

2022-05-13 11:29 UTC, NikVolf commented on gear-test/src/ext.rs
> +    fn new(
No need in such giant new function, just initialize structure by-field

2022-05-30 17:03 UTC, grishasobol requested changes

2022-05-30 17:03 UTC, grishasobol commented on pallets/gear/src/ext.rs
> +        }
А если мы решим собрать ноду без lazy-pages?

2022-05-30 17:04 UTC, grishasobol commented on core-processor/src/executor.rs
> -    if !A::check_lazy_pages_consistent_state() {
Can see now that it's not support two regime. But it must because we can build node with no lazy-pages feature.

2022-05-31 18:58 UTC, grishasobol approved these changes

2022-06-21 12:43 UTC, closed without merging