Add list of forbidden syscalls to WASM executor
gear-tech/gear pull request #959
Opened 2022-05-23 15:41 UTC by shamilsan

Finally resolves #587.

- Add functions (aka syscalls) blacklist.
- Generate a trap when trying to call a forbidden function in a program.
- Forbid to call `gr_gas_available` when executing WASM from `get_gas_spent` function.

https://github.com/orgs/gear-tech/teams/dev

2022-05-24 08:14 UTC, shamilsan commented
> Can you describe in the pr description use case for that?

Added it.

2022-05-24 09:05 UTC, NikVolf commented
So the end-user usecase will be that you show that gas cannot be calculated or what?

Add this as well maybe

2022-05-24 11:05 UTC, shamilsan commented
> So the end-user usecase will be that you show that gas cannot be calculated or what?

Yes at the moment. But there are potential use cases in the future.

> Add this as well maybe

Done.

2022-05-24 11:15 UTC, breathx commented
@NikVolf one more case for future is to forbid usage of sending syscalls in signals handling #647

2022-05-26 18:03 UTC, breathx requested changes
Research that moment with overriding host functions, please, and merge `master`.

2022-05-26 18:03 UTC, breathx commented
Otherwise, great!

2022-06-08 13:55 UTC, shamilsan commented on core-processor/src/configs.rs
> +    pub forbidden_funcs: Vec<&'static str>,
Fixed

2022-06-08 13:55 UTC, shamilsan commented on core-processor/src/configs.rs
> +    pub forbidden_funcs: Vec<&'static str>,
Fixed

2022-06-08 13:56 UTC, shamilsan commented on core-backend/sandbox/src/env.rs
> +            .for_each(|f| env_builder.add_host_func("env", *f, funcs::forbidden));
Fixed

2022-06-08 14:56 UTC, breathx approved these changes

2022-06-08 14:56 UTC, breathx commented on core/src/env.rs
> +    struct ExtImplementedStruct(u8, BTreeSet<&'static str>);
Seems useless

2022-06-08 14:56 UTC, breathx commented on core/src/env.rs
> +    #[derive(Debug, PartialEq, Eq, Clone, Default)] //, Copy)]
```suggestion
    #[derive(Debug, PartialEq, Eq, Clone, Default)]
```

dead code

2022-06-08 14:56 UTC, breathx commented on core-backend/sandbox/src/env.rs
> +                .add_host_func("env", name, crate::funcs::FuncsHandler::forbidden);
```suggestion
                .add_host_func("env", name, FuncsHandler::forbidden);
```

Move import on top of the file

2022-06-08 16:30 UTC, shamilsan commented on core-backend/sandbox/src/env.rs
> +                .add_host_func("env", name, crate::funcs::FuncsHandler::forbidden);
Yes, my fault, fixed.

2022-06-08 16:32 UTC, shamilsan commented on core/src/env.rs
> +    #[derive(Debug, PartialEq, Eq, Clone, Default)] //, Copy)]
Blind eye, repaired.

2022-06-08 16:53 UTC, merged