fix wasmer backend
gear-tech/gear pull request #968
Opened 2022-05-25 16:38 UTC by grishasobol

fix wasmer backend:
Later we unprotect pages after memory deallocation (memory move causes memory deallocation and we cannot touch pages after that)

2022-05-25 21:33 UTC, breathx commented
First of all, how does `wasmtime` affect `wasmer` issue, or it's just wrong PR name?
Secondly, could you explain what's the difference of using method or copy-pasting code? Some tests would be great too

2022-05-26 06:14 UTC, gshep commented
> First of all, how does `wasmtime` affect `wasmer` issue, or it's just wrong PR name? Secondly, could you explain what's the difference of using method or copy-pasting code? Some tests would be great too

If I understand correctly then the issue is that when `self` is moved into the method and destructured all items after that are deallocated (for example `store` & `memory`).

I would suggest to return these items as the method result so their lifetime could be extended to avoid copypasting:
```rust
fn prepare_post_execution_data(
        self,
    ) -> Result<(ExtInfo, HostPointer, StoreType, MemroyType), BackendError<WasmtimeEnvironmentError>> {
         /* ... */
            .map(|info| (info, wasm_memory_addr, store, memory))
    }
```

and then:
```rust
let (ext, wasm_addr, _store, _memory) = object.prepare_post_execution_data()?;
```

2022-05-26 06:16 UTC, gshep commented on core-backend/wasmtime/src/env.rs
> +            .map(|info| (info, wasm_memory_addr))?;
I don't know what the way you're gonna go however the map in this case is unnecessary.

2022-05-26 08:37 UTC, grishasobol commented
> First of all, how does `wasmtime` affect `wasmer` issue, or it's just wrong PR name? Secondly, could you explain what's the difference of using method or copy-pasting code? Some tests would be great too

Yes it's wrong name: wasmtime must be

2022-05-26 16:15 UTC, grishasobol commented
> First of all, how does `wasmtime` affect `wasmer` issue, or it's just wrong PR name? Secondly, could you explain what's the difference of using method or copy-pasting code? Some tests would be great too

We move memory and then drop memory before. Now memory live until the end of function

2022-05-26 17:50 UTC, SabaunT requested changes

2022-05-26 17:50 UTC, SabaunT commented on examples/ping-gas/src/lib.rs
> +
?

2022-05-26 17:50 UTC, SabaunT commented on examples/ping-gas/src/lib.rs
> +    // let mVut a = A;
same

2022-05-27 05:04 UTC, gshep approved these changes

2022-05-27 11:48 UTC, gshep approved these changes

2022-05-27 12:10 UTC, SabaunT approved these changes
Discussed

2022-05-27 12:30 UTC, merged